<?php require __DIR__.'/lib/bootstrap.php';$support=app_setting('support_email','');$version=legal_version('cancellation');?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cancelamentos e Reembolsos • <?=e(site_name())?></title><link rel="stylesheet" href="assets/css/site.css"><style><?=brand_css_vars()?></style><style>.legal-page{max-width:920px;margin:auto;padding:140px 24px 90px}.legal-page h1{font:700 clamp(2.8rem,7vw,5rem)/1 'Oswald';text-transform:uppercase}.legal-page h2{margin-top:34px}.legal-page li{margin:8px 0}.legal-meta{color:#8a7a70}</style></head><body><header class="topbar compact"><a class="brand" href="index.php"><img src="<?=e(brand_logo())?>" alt="<?=e(site_name())?>"></a></header><main class="legal-page"><span class="eyebrow dark">COMPRAS</span><h1>Cancelamentos e Reembolsos</h1><p class="legal-meta">Versão <?=e($version)?>.</p>
<p>Esta política deve ser interpretada em conjunto com a legislação de proteção ao consumidor aplicável e com as condições específicas divulgadas para cada evento.</p>
<h2>1. Solicitação pelo comprador</h2><p>Solicitações devem ser feitas pelo canal oficial de atendimento, informando número do pedido e dados do comprador. A análise considera a data da compra, a data do evento e os direitos legais aplicáveis, inclusive eventual direito de arrependimento quando cabível.</p>
<h2>2. Evento cancelado</h2><p>Se o evento for cancelado pela organização, os compradores afetados serão informados pelos canais disponíveis e receberão orientação sobre reembolso ou solução aplicável.</p>
<h2>3. Evento alterado</h2><p>Alterações relevantes serão comunicadas quando possível. Eventuais opções de cancelamento ou reembolso observarão a legislação aplicável e a natureza da alteração.</p>
<h2>4. Reembolso</h2><p>Quando aprovado, o reembolso é solicitado ao mesmo provedor de pagamento utilizado na compra. O prazo de crédito pode depender da instituição financeira, bandeira ou meio de pagamento. Após o reembolso, os ingressos do pedido são invalidados.</p>
<h2>5. Ingresso já utilizado</h2><p>Ingressos já utilizados no check-in não são elegíveis a reembolso por simples desistência após a entrada, sem prejuízo de direitos legais específicos.</p>
<h2>6. Atendimento</h2><p><?= $support!==''?'Contato: <a href="mailto:'.e($support).'">'.e($support).'</a>.':'Utilize os canais oficiais da organização.' ?></p><p><a class="btn btn-dark" href="index.php">Voltar ao site</a></p></main></body></html>
