<?php
require __DIR__ . '/lib/bootstrap.php';
$event = event_by_slug(trim($_GET['slug'] ?? ''));
if (!$event) { http_response_code(404); exit('Evento não encontrado.'); }
$salesOpen=event_sales_open($event);$types=$salesOpen?array_values(array_filter(ticket_types((int)$event['id'],true),fn($t)=>ticket_available($t)>0)):[];$maxQty=max(1,min(20,(int)($event['max_tickets_per_order']??8)));
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="<?=e(sanitize_hex_color(app_setting('brand_night','#100908'),'#100908'))?>"><title><?=e($event['title'])?> • <?=e(site_name())?></title><link rel="stylesheet" href="assets/css/site.css"><style><?=brand_css_vars()?></style></head><body class="event-page">
<header class="topbar compact" data-header><a class="brand" href="index.php"><img src="<?=e(brand_logo())?>" alt="<?=e(site_name())?>"></a><nav id="site-nav"><a href="index.php#agenda">Agenda</a><a href="index.php#casa">A casa</a><a href="vip-check.php?event=<?=intval($event['id'])?>">Lista VIP</a></nav><button class="menu-btn" aria-label="Abrir menu" aria-controls="site-nav" aria-expanded="false"><span></span><span></span></button></header>
<main class="event-detail">
<section class="event-detail-hero"<?=!empty($event['cover_image'])?' style="--event-cover:url(\''.e($event['cover_image']).'\')"':''?>>
  <div class="event-detail-bg"></div><div class="event-detail-shade"></div>
  <div class="event-detail-content reveal"><a href="index.php#agenda" class="event-back">← Voltar para agenda</a><span class="eyebrow">EVENTO OFICIAL • <?=e(mb_strtoupper(site_name()))?></span><h1><?=e($event['title'])?></h1><div class="detail-meta"><span><?=e(weekday_br($event['event_date']))?>, <?=e((new DateTime($event['event_date']))->format('d'))?> <?=e(month_short_br($event['event_date']))?> • <?=e((new DateTime($event['event_date']))->format('H:i'))?></span><span><?=e($event['venue'] ?: site_name())?></span></div><?php if(trim((string)$event['description'])!==''):?><p><?=nl2br(e($event['description']))?></p><?php endif;?><a class="btn btn-primary mobile-buy" href="#ingressos">Comprar ingresso</a></div>
  <div class="event-date-big reveal"><span><?=e(weekday_br($event['event_date']))?></span><strong><?=e((new DateTime($event['event_date']))->format('d'))?></strong><b><?=e(month_short_br($event['event_date']))?> / <?=e((new DateTime($event['event_date']))->format('Y'))?></b></div>
</section>

<section id="ingressos" class="event-purchase">
  <div class="ticket-panel reveal"><span class="eyebrow dark">INGRESSOS</span><h2>Escolha seu lote</h2><p class="panel-intro">Selecione uma opção disponível e finalize sua compra em poucos passos.</p>
  <?php if (!$salesOpen): ?><div class="alert error">As vendas online estão encerradas ou ainda não começaram.</div><?php elseif (!$types): ?><div class="alert error">Ingressos esgotados ou indisponíveis para este evento.</div><?php else: ?><form method="get" action="checkout.php" class="ticket-form"><input type="hidden" name="event" value="<?=intval($event['id'])?>">
  <div class="ticket-options"><?php foreach ($types as $type): $available=(int)$type['stock']-(int)$type['sold']; ?><label class="ticket-option"><input type="radio" name="type" value="<?=intval($type['id'])?>" required><span class="ticket-radio"></span><span class="ticket-option-copy"><b><?=e($type['name'])?></b><small><?=e($type['description'] ?: 'Ingresso individual')?> · <?=intval($available)?> disponíveis</small></span><strong><?=money((float)$type['price'])?></strong></label><?php endforeach; ?></div>
  <div class="ticket-buy-row"><label class="qty-field"><span>Quantidade</span><select name="qty"><?php for($i=1;$i<=$maxQty;$i++):?><option><?=$i?></option><?php endfor;?></select></label><button class="btn btn-primary">Continuar compra <span>→</span></button></div></form><?php endif; ?>
  </div>
  <aside class="event-info-panel reveal"><span class="eyebrow dark">INFORMAÇÕES</span><h3>Prepare sua noite</h3><div class="info-row"><small>DATA E HORA</small><strong><?=e(dt_br($event['event_date']))?></strong></div><div class="info-row"><small>LOCAL</small><strong><?=e($event['venue'] ?: site_name())?></strong></div><div class="info-row"><small>ENDEREÇO</small><strong><?=e($event['address'] ?: app_setting('address',$config['address']??''))?></strong></div><?php if($event['doors_time']):?><div class="info-row"><small>ABERTURA DA CASA</small><strong><?=e($event['doors_time'])?></strong></div><?php endif; ?><div class="info-row"><small>CLASSIFICAÇÃO</small><strong><?=intval($event['minimum_age']??18)>0?intval($event['minimum_age']).' anos':'Livre'?></strong></div><?php if($event['vip_enabled']):?><div class="vip-mini"><span>★</span><div><b>Lista VIP ativa</b><p>Consulte seu nome antes do evento.</p><a href="vip-check.php?event=<?=intval($event['id'])?>">Consultar VIP →</a></div></div><?php endif;?></aside>
</section>
</main>
<footer class="simple-footer"><a href="index.php">← Voltar para o site</a><span>© <?=date('Y')?> <?=e(site_name())?></span></footer><script src="assets/js/app.js"></script></body></html>
