<?php
require __DIR__ . '/lib/bootstrap.php';
$events = db()->query("SELECT * FROM events WHERE status='published' AND datetime(event_date) >= datetime('now','-1 day') ORDER BY datetime(event_date) ASC LIMIT 12")->fetchAll();
$featured = $events[0] ?? null;
$flashes = get_flashes();
$name=site_name();$tagline=site_tagline();
$city=app_setting('site_city_state','SUA CIDADE / UF');$since=app_setting('site_since','DESDE 20XX');
$description=app_setting('site_description','Eventos, ingressos online e Lista VIP.');
$publicPhone=app_setting('contact_phone',$config['contact_phone']??'');
$publicInstagram=app_setting('contact_instagram',$config['contact_instagram']??'@seuinstagram');
$instagramUrl=trim(app_setting('instagram_url',$config['instagram_url']??''));
if($instagramUrl==='' && $publicInstagram!=='' && $publicInstagram!=='@seuinstagram')$instagramUrl='https://www.instagram.com/'.ltrim($publicInstagram,'@/').'/';
$address=app_setting('address',$config['address']??'COLOQUE SEU ENDEREÇO AQUI');
$mapsUrl=app_setting('maps_url',$config['maps_url']??'');
$logo=brand_logo();$hero=brand_media('hero_image','assets/media/placeholder-hero.svg');$about=brand_media('about_image','assets/media/placeholder-about.svg');$interior=brand_media('interior_image','assets/media/placeholder-interior.svg');$gallery1=brand_media('gallery_image_1','assets/media/placeholder-gallery-1.svg');$gallery2=brand_media('gallery_image_2','assets/media/placeholder-gallery-2.svg');$locationImg=brand_media('location_image','assets/media/placeholder-location.svg');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="<?=e(sanitize_hex_color(app_setting('brand_night','#100908'),'#100908'))?>"><meta name="description" content="<?=e($description)?>"><title><?=e($name)?> • Eventos & Ingressos</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="assets/css/site.css"><style><?=brand_css_vars()?></style></head><body>
<header class="topbar" data-header><a class="brand" href="index.php" aria-label="<?=e($name)?> — início"><img src="<?=e($logo)?>" alt="<?=e($name)?>"></a><nav id="site-nav"><a href="#agenda">Agenda</a><a href="#casa">A casa</a><a href="#experiencia">Experiência</a><a href="#local">Como chegar</a><a href="vip-check.php">Lista VIP</a><a href="pedido.php">Meus ingressos</a><a class="nav-ticket" href="#agenda">Comprar</a></nav><button class="menu-btn" aria-label="Abrir menu" aria-controls="site-nav" aria-expanded="false"><span></span><span></span></button></header>
<?php foreach($flashes as $f):?><div class="flash <?=e($f['type'])?>"><?=e($f['message'])?></div><?php endforeach;?>
<main>
<section class="hero-home"><div class="hero-home-media" style="background-image:url('<?=e($hero)?>')" aria-hidden="true"></div><div class="hero-home-shade" aria-hidden="true"></div><div class="hero-grain" aria-hidden="true"></div><div class="hero-home-content reveal"><span class="eyebrow"><?=e(app_setting('hero_kicker',$city.' · '.$since))?></span><img src="<?=e($logo)?>" alt="<?=e($name)?>" class="hero-logo-mark"><h1><?=e(app_setting('hero_title','Sua próxima noite'))?><br><em><?=e(app_setting('hero_highlight','começa aqui.'))?></em></h1><p><?=e(app_setting('hero_text','Shows, festas e experiências com venda de ingressos online, Lista VIP e entrada digital.'))?></p><div class="hero-actions"><a class="btn btn-primary" href="#agenda">Ver agenda <span>↗</span></a><a class="btn btn-glass" href="vip-check.php">Consultar Lista VIP</a></div></div><a class="hero-scroll" href="#agenda"><span></span>Role para descobrir</a></section>
<section class="marquee" aria-label="Destaques"><div class="marquee-track"><span>EVENTOS</span><b>✦</b><span>INGRESSOS ONLINE</span><b>✦</b><span>LISTA VIP</span><b>✦</b><span>CHECK-IN COM QR CODE</span><b>✦</b><span><?=e($city)?></span><b>✦</b><span>EVENTOS</span><b>✦</b><span>INGRESSOS ONLINE</span><b>✦</b><span>LISTA VIP</span><b>✦</b><span>CHECK-IN COM QR CODE</span><b>✦</b><span><?=e($city)?></span></div></section>
<?php if($featured):?><section class="featured-event-band" aria-label="Próximo evento"><a class="next-event-card reveal" href="event.php?slug=<?=urlencode($featured['slug'])?>"><span class="next-event-kicker">PRÓXIMO EVENTO</span><div class="next-event-date"><b><?=e((new DateTime($featured['event_date']))->format('d'))?></b><span><?=e(month_short_br($featured['event_date']))?></span></div><div class="next-event-copy"><strong><?=e($featured['title'])?></strong><small><?=e(weekday_br($featured['event_date']))?> • <?=e((new DateTime($featured['event_date']))->format('H:i'))?> · ver detalhes</small></div><span class="next-event-arrow">→</span></a></section><?php endif;?>
<section id="agenda" class="section agenda-section"><div class="section-title-row reveal"><div><span class="eyebrow dark">PRÓXIMOS EVENTOS</span><h2>Escolha sua<br><em>próxima experiência.</em></h2></div><div class="section-intro"><p>Ingressos oficiais, lotes e disponibilidade em tempo real. Compre online e apresente seu ingresso digital na entrada.</p><a href="vip-check.php" class="under-link">Já está na lista? Consulte a VIP →</a></div></div><div class="event-grid">
<?php if(!$events):?><div class="empty-state reveal"><span>✦</span><h3>Cadastre seus eventos</h3><p>O administrador cria eventos, lotes, preços, estoque e Lista VIP pelo painel.</p></div><?php endif;?>
<?php foreach($events as $i=>$ev):$types=ticket_types((int)$ev['id']);$availableTypes=array_values(array_filter($types,fn($t)=>(int)$t['active']===1&&(int)$t['stock']>(int)$t['sold']));$min=$availableTypes?min(array_map(fn($t)=>(float)$t['price'],$availableTypes)):0;$cover=$ev['cover_image']?:'assets/media/placeholder-gallery-1.svg';?><article class="event-card reveal" style="--delay:<?=min($i,5)*70?>ms"><a href="event.php?slug=<?=urlencode($ev['slug'])?>" class="event-card-media" style="background-image:url('<?=e($cover)?>')"><div class="event-card-overlay"></div><div class="date-badge"><small><?=e(weekday_br($ev['event_date']))?></small><strong><?=e((new DateTime($ev['event_date']))->format('d'))?></strong><span><?=e(month_short_br($ev['event_date']))?></span></div><span class="event-hover">Ver evento <b>↗</b></span></a><div class="event-card-body"><div class="event-meta"><?=e((new DateTime($ev['event_date']))->format('H:i'))?> • <?=e($ev['venue']?:$name)?></div><h3><a href="event.php?slug=<?=urlencode($ev['slug'])?>"><?=e($ev['title'])?></a></h3><div class="event-card-footer"><span><?=$min>0?'Ingressos desde <b>'.money($min).'</b>':'<b>Confira os detalhes</b>'?></span><a class="circle-link" href="event.php?slug=<?=urlencode($ev['slug'])?>" aria-label="Abrir evento">→</a></div></div></article><?php endforeach;?></div></section>
<section id="casa" class="story-section"><div class="story-media reveal"><img src="<?=e($about)?>" alt="Foto institucional de <?=e($name)?>" loading="lazy"><span class="photo-caption"><?=e(mb_strtoupper($name))?> · <?=e(mb_strtoupper($city))?></span></div><div class="story-copy reveal"><span class="eyebrow"><?=e(app_setting('about_kicker','SOBRE O SEU ESPAÇO'))?></span><h2><?=e(app_setting('about_title','Conte a história'))?><br><em><?=e(app_setting('about_highlight','da sua marca.'))?></em></h2><p class="lead"><?=e(app_setting('about_text','Use este espaço para apresentar sua casa, bar, balada, arena, festival ou projeto de eventos. Troque o texto e as fotos pelo painel administrativo.'))?></p><div class="story-facts"><div><strong>EVENTOS</strong><span>agenda administrável</span></div><div><strong>VIP</strong><span>lista por evento</span></div><div><strong>QR CODE</strong><span>entrada digital</span></div></div><a class="btn btn-outline-light" href="#local">Como chegar</a></div></section>
<section class="inside-showcase" aria-label="Experiência"><img src="<?=e($interior)?>" alt="Imagem de destaque de <?=e($name)?>" loading="lazy"><div class="inside-showcase-shade" aria-hidden="true"></div><div class="inside-showcase-copy reveal"><span class="eyebrow"><?=e(app_setting('inside_kicker','SUA EXPERIÊNCIA'))?></span><h2><?=e(app_setting('inside_title','Mostre o que faz'))?><br><em><?=e(app_setting('inside_highlight','seu lugar único.'))?></em></h2><p><?=e(app_setting('inside_text','Inclua uma foto ampla do ambiente, palco, pista, camarotes ou qualquer elemento que represente sua experiência.'))?></p><a class="btn btn-outline-light" href="#agenda">Ver próximos eventos</a></div></section>
<section id="experiencia" class="section experience-section"><div class="section-title-row reveal"><div><span class="eyebrow dark">EXPERIÊNCIA COMPLETA</span><h2>Seu evento.<br><em>Seu jeito.</em></h2></div><p class="section-intro plain">A estrutura é genérica e pode ser usada por casas de shows, bares, baladas, festivais, festas, arenas e produtores.</p></div><div class="experience-grid"><article class="experience-card reveal"><span>01</span><div class="experience-icon">♬</div><h3>Eventos & agenda</h3><p>Crie eventos, publique capas, datas, informações, classificação e programação.</p></article><article class="experience-card reveal"><span>02</span><div class="experience-icon">$</div><h3>Ingressos online</h3><p>Crie lotes, preços e estoques com pagamento online preparado para Mercado Pago.</p></article><article class="experience-card reveal"><span>03</span><div class="experience-icon">★</div><h3>Lista VIP</h3><p>Gerencie nomes, acompanhantes, importação e entrada separadamente por evento.</p></article><article class="experience-card reveal"><span>04</span><div class="experience-icon">✓</div><h3>Portaria digital</h3><p>Ingressos com QR Code e validação pela câmera do celular, com bloqueio de reutilização.</p></article></div></section>
<section class="gallery-section"><div class="gallery-copy reveal"><span class="eyebrow">SUA GALERIA</span><h2><?=e(app_setting('gallery_title','Suas noites.'))?><br><em><?=e(app_setting('gallery_highlight','Suas fotos.'))?></em></h2><p><?=e(app_setting('gallery_text','Substitua estas imagens por fotos reais dos seus eventos, artistas, público e estrutura.'))?></p><?php if($instagramUrl):?><a href="<?=e($instagramUrl)?>" target="_blank" rel="noopener" class="under-link light">Ver <?=e($publicInstagram)?> →</a><?php endif;?></div><div class="gallery-grid"><figure class="gallery-wide reveal"><img src="<?=e($gallery1)?>" alt="Galeria 1" loading="lazy"><figcaption>COLOQUE SUA FOTO AQUI</figcaption></figure><figure class="gallery-tall reveal"><img src="<?=e($gallery2)?>" alt="Galeria 2" loading="lazy"><figcaption>COLOQUE SUA FOTO AQUI</figcaption></figure></div></section>
<section class="vip-banner"><div class="vip-banner-art" aria-hidden="true">VIP</div><div class="vip-banner-copy reveal"><span class="eyebrow">LISTA VIP</span><h2>Seu nome já<br>está na lista?</h2><p>A Lista VIP é criada e administrada pela produção de cada evento. Consulte seu cadastro antes de sair de casa.</p><a class="btn btn-light" href="vip-check.php">Consultar agora <span>→</span></a></div></section>
<section id="local" class="location-section"><div class="location-copy reveal"><span class="eyebrow dark">ONDE A EXPERIÊNCIA ACONTECE</span><h2><?=e(app_setting('location_title','Nos vemos'))?><br> <em><?=e(app_setting('location_highlight','no seu evento.'))?></em></h2><div class="location-info"><div><small>ENDEREÇO</small><strong><?=e($address)?></strong></div><div><small>PROGRAMAÇÃO</small><strong><?=e(app_setting('programming_text','Datas e horários conforme a programação de cada evento.'))?></strong></div><div><small>CONTATO</small><strong><?=e($publicPhone?:'COLOQUE SEU TELEFONE')?></strong><?php if($instagramUrl):?><a href="<?=e($instagramUrl)?>" target="_blank" rel="noopener"><?=e($publicInstagram)?></a><?php endif;?></div></div><div class="location-actions"><?php if($mapsUrl):?><a class="btn btn-dark" href="<?=e($mapsUrl)?>" target="_blank" rel="noopener">Abrir no mapa ↗</a><?php endif;?><a class="btn btn-outline-dark" href="#agenda">Ver eventos</a></div></div><a class="location-photo reveal" href="<?=$mapsUrl?e($mapsUrl):'#'?>" <?=$mapsUrl?'target="_blank" rel="noopener"':''?>><img src="<?=e($locationImg)?>" alt="Local do evento" loading="lazy"><span class="map-pin"><?=e(mb_strtoupper($name))?><br><small><?=e(mb_strtoupper($city))?></small></span></a></section>
<section class="faq-section section"><div class="faq-head reveal"><span class="eyebrow dark">DÚVIDAS RÁPIDAS</span><h2>Antes de<br><em>chegar.</em></h2></div><div class="faq-list"><details class="reveal"><summary>Como compro ingresso online?<span>+</span></summary><p>Abra o evento desejado, selecione o lote e a quantidade, preencha seus dados e siga para o pagamento. Após a confirmação, seu ingresso digital fica disponível.</p></details><details class="reveal"><summary>Como funciona a Lista VIP?<span>+</span></summary><p>A lista é administrada pela produção de cada evento. No site o visitante pode consultar se seu cadastro está ativo.</p></details><details class="reveal"><summary>Preciso imprimir o ingresso?<span>+</span></summary><p>Não. O ingresso é digital e pode ser apresentado no celular por QR Code.</p></details><details class="reveal"><summary>Onde encontro as informações do evento?<span>+</span></summary><p>Cada evento possui uma página própria com data, horário, local, endereço, classificação e lotes disponíveis.</p></details></div></section>
</main>
<footer class="site-footer"><div class="footer-top"><div class="footer-brand"><img src="<?=e($logo)?>" alt="<?=e($name)?>"><p><?=e($tagline)?></p></div><div class="footer-col"><small>NAVEGUE</small><a href="#agenda">Agenda</a><a href="#casa">A casa</a><a href="vip-check.php">Lista VIP</a><a href="pedido.php">Meus ingressos</a><a href="termos.php">Termos</a><a href="privacidade.php">Privacidade</a><a href="cancelamento.php">Cancelamentos</a><a href="admin/login.php">Administração</a></div><div class="footer-col"><small>CONTATO</small><?php if($instagramUrl):?><a href="<?=e($instagramUrl)?>" target="_blank" rel="noopener"><?=e($publicInstagram)?></a><?php endif;?><?php if($publicPhone):?><a href="tel:<?=e($publicPhone)?>"><?=e($publicPhone)?></a><?php endif;?><?php if($mapsUrl):?><a href="<?=e($mapsUrl)?>" target="_blank" rel="noopener">Como chegar ↗</a><?php endif;?></div><div class="footer-address"><small><?=e(mb_strtoupper($city))?></small><p><?=e($address)?></p></div></div><div class="footer-bottom"><span>© <?=date('Y')?> <?=e($name)?></span><span>Plataforma de eventos por <b>CACTUS</b></span></div></footer><script src="assets/js/app.js"></script></body></html>
