<?php require __DIR__.'/lib/bootstrap.php';
$token=trim($_GET['token']??'');
$st=db()->prepare('SELECT o.*,e.title event_title,e.event_date,e.slug FROM orders o JOIN events e ON e.id=o.event_id WHERE o.public_token=?');$st->execute([$token]);$order=$st->fetch();
if(!$order){http_response_code(404);exit('Pedido não encontrado.');}
// Acelera a confirmação no retorno do Mercado Pago; o webhook continua sendo a fonte automática principal.
$paymentId=(string)($_GET['payment_id']??$_GET['collection_id']??'');
if($paymentId!=='' && $order['payment_mode']==='mercadopago' && $order['status']==='pending'){
    try{$payment=mp_request('GET','/v1/payments/'.rawurlencode($paymentId));if(validate_mp_payment_for_order($payment,$order)){mark_order_paid((int)$order['id'],$paymentId);$st->execute([$token]);$order=$st->fetch();}}catch(Throwable $ignored){}
}
$flashes=get_flashes();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pedido <?=e($order['order_number'])?> • <?=e(site_name())?></title><link rel="stylesheet" href="assets/css/site.css"><style><?=brand_css_vars()?></style></head><body class="dark-page"><header class="topbar compact"><a class="brand" href="index.php"><img src="<?=e(brand_logo())?>" alt="<?=e(site_name())?>"></a></header><main class="status-page"><div class="status-card"><?php foreach($flashes as $f):?><div class="alert <?=e($f['type'])?>"><?=e($f['message'])?></div><?php endforeach;?><span class="status-icon <?=e($order['status'])?>"><?= $order['status']==='paid'?'✓':($order['status']==='expired'?'×':'⌛') ?></span><span class="eyebrow dark">PEDIDO <?=e($order['order_number'])?></span><h1><?= $order['status']==='paid'?'Pagamento confirmado':($order['status']==='review'?'Pagamento em revisão':($order['status']==='expired'?'Reserva expirada':'Pedido recebido')) ?></h1><p><b><?=e($order['event_title'])?></b><br><?=e(dt_br($order['event_date']))?></p><div class="order-lines"><span>Status <b><?=e(status_label($order['status']))?></b></span><span>Total <b><?=money((float)$order['total'])?></b></span></div><?php if($order['status']==='paid'):?><p>Seus ingressos já foram emitidos. O e-mail transacional também foi colocado na fila.</p><a class="btn btn-primary" href="ticket.php?token=<?=urlencode($order['public_token'])?>">Ver meus ingressos</a><?php elseif($order['status']==='review'):?><div class="alert error"><b>Pagamento identificado.</b> A reserva havia expirado e o estoque não estava mais disponível. Seu pedido está em revisão manual e nenhum ingresso duplicado foi emitido.</div><p>A equipe responsável fará a regularização ou reembolso conforme a disponibilidade.</p><?php elseif($order['status']==='pending'):?><p><?= $order['payment_mode']==='manual'?'A equipe poderá confirmar o pagamento no painel administrativo.':'A confirmação é automática após a aprovação do Mercado Pago.' ?></p><?php if($order['checkout_url']):?><a class="btn btn-primary" href="<?=e($order['checkout_url'])?>">Continuar pagamento</a><?php endif;?><?php else:?><p>Este pedido não está mais ativo. Volte ao evento para fazer uma nova compra.</p><?php endif;?><a class="btn btn-ghost dark-outline" href="index.php">Voltar ao site</a></div></main></body></html>
