<?php require __DIR__.'/lib/bootstrap.php';$legal=app_setting('legal_name',site_name());$doc=app_setting('legal_document','');$email=app_setting('privacy_email',app_setting('support_email',''));$version=legal_version('privacy');?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Política de Privacidade • <?=e(site_name())?></title><link rel="stylesheet" href="assets/css/site.css"><style><?=brand_css_vars()?></style><style>.legal-page{max-width:920px;margin:auto;padding:140px 24px 90px}.legal-page h1{font:700 clamp(2.8rem,7vw,5rem)/1 'Oswald';text-transform:uppercase}.legal-page h2{margin-top:34px}.legal-page li{margin:8px 0}.legal-meta{color:#8a7a70}</style></head><body><header class="topbar compact"><a class="brand" href="index.php"><img src="<?=e(brand_logo())?>" alt="<?=e(site_name())?>"></a></header><main class="legal-page"><span class="eyebrow dark">LGPD • PRIVACIDADE</span><h1>Política de Privacidade</h1><p class="legal-meta">Versão <?=e($version)?>.</p><p>Esta política explica como <b><?=e($legal)?></b><?= $doc!==''?' ('.e($doc).')':'' ?> trata dados pessoais usados no site de eventos, ingressos e Lista VIP.</p>
<h2>1. Dados tratados</h2><p>Podemos tratar nome, e-mail, telefone, documento informado no checkout, dados do pedido, evento, ingresso, registros de acesso e check-in, IP, informações técnicas do navegador e registros de consentimento. Dados de pagamento são processados pelo provedor de pagamento; o site não armazena o número completo do cartão.</p>
<h2>2. Finalidades</h2><ul><li>processar reservas, pagamentos e emissão de ingressos;</li><li>enviar confirmações e comunicações transacionais;</li><li>controlar estoque, Lista VIP e acesso ao evento;</li><li>prevenir fraude, duplicidade de ingresso e incidentes de segurança;</li><li>cumprir obrigações legais, fiscais e de defesa de direitos;</li><li>enviar marketing somente quando houver opção separada de consentimento ou outra base legal aplicável.</li></ul>
<h2>3. Compartilhamento</h2><p>Os dados podem ser compartilhados, quando necessário, com provedores de pagamento, hospedagem, e-mail, suporte técnico e autoridades competentes, sempre limitados à finalidade correspondente.</p>
<h2>4. Retenção e segurança</h2><p>Os dados são mantidos pelo tempo necessário para executar o contrato, atender obrigações legais e resguardar direitos. O sistema utiliza controles de acesso, senhas protegidas, CSRF, registros de auditoria e restrições de acesso aos arquivos internos.</p>
<h2>5. Direitos do titular</h2><p>Nos termos da legislação aplicável, o titular pode solicitar confirmação de tratamento, acesso, correção, informações sobre compartilhamento e, quando cabível, eliminação, anonimização, portabilidade, oposição ou revogação de consentimento.</p>
<h2>6. Contato</h2><p>Para assuntos de privacidade, use <?= $email!==''?'<a href="mailto:'.e($email).'">'.e($email).'</a>':'o canal de atendimento oficial da organização' ?>.</p>
<h2>7. Atualizações</h2><p>A política pode ser atualizada. Em compras online, o sistema registra a versão aceita no momento do checkout.</p><p><a class="btn btn-dark" href="index.php">Voltar ao site</a></p></main></body></html>
