<?php require __DIR__.'/lib/bootstrap.php';$legal=app_setting('legal_name',site_name());$doc=app_setting('legal_document','');$support=app_setting('support_email','');$version=legal_version('terms');?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Termos de Uso e Compra • <?=e(site_name())?></title><link rel="stylesheet" href="assets/css/site.css"><style><?=brand_css_vars()?></style><style>.legal-page{max-width:920px;margin:auto;padding:140px 24px 90px}.legal-page h1{font:700 clamp(2.8rem,7vw,5rem)/1 'Oswald';text-transform:uppercase}.legal-page h2{margin-top:34px}.legal-page li{margin:8px 0}.legal-meta{color:#8a7a70}</style></head><body><header class="topbar compact"><a class="brand" href="index.php"><img src="<?=e(brand_logo())?>" alt="<?=e(site_name())?>"></a></header><main class="legal-page"><span class="eyebrow dark">TERMOS</span><h1>Termos de Uso e Compra</h1><p class="legal-meta">Versão <?=e($version)?>.</p><p>Estes termos regulam o uso da plataforma de eventos e ingressos de <b><?=e($legal)?></b><?= $doc!==''?' ('.e($doc).')':'' ?>.</p>
<h2>1. Cadastro e compra</h2><p>O comprador deve fornecer dados verdadeiros e manter o link do pedido e os ingressos sob sua responsabilidade. A compra só é considerada confirmada após a aprovação do pagamento e a emissão do ingresso, salvo operação manual registrada pela administração.</p>
<h2>2. Ingressos</h2><p>Cada ingresso possui código único e QR Code de uso único. O primeiro check-in válido torna o ingresso utilizado. Compartilhar, publicar ou duplicar o QR Code pode impedir a entrada de quem apresentar uma cópia posterior.</p>
<h2>3. Estoque e reserva</h2><p>Durante o checkout, o sistema pode reservar temporariamente o estoque. Se o pagamento não for concluído no prazo indicado, a reserva pode expirar e o ingresso voltar à venda. Caso um pagamento seja confirmado após a expiração e o estoque não esteja mais disponível, o pedido entra em revisão para regularização ou reembolso.</p>
<h2>4. Regras do evento</h2><p>O acesso depende do ingresso válido e das regras informadas para o evento, incluindo classificação etária, documentos exigidos e condições de segurança. Horários, atrações e informações operacionais podem sofrer alterações quando justificadas, observados os direitos do consumidor aplicáveis.</p>
<h2>5. Cancelamento e reembolso</h2><p>Aplicam-se a política publicada em <a href="cancelamento.php">Cancelamentos e Reembolsos</a> e os direitos previstos na legislação aplicável.</p>
<h2>6. Uso da plataforma</h2><p>É proibido tentar burlar pagamentos, estoque, autenticação, QR Codes, controles de acesso ou qualquer mecanismo de segurança.</p>
<h2>7. Atendimento</h2><p><?= $support!==''?'Contato: <a href="mailto:'.e($support).'">'.e($support).'</a>.':'Utilize os canais oficiais da organização.' ?></p><p><a class="btn btn-dark" href="index.php">Voltar ao site</a></p></main></body></html>
