const CATALOG_KEY="dbarros_catalog_v3";
const DELIVERY_KEY="dbarros_delivery_site_v2";
const DEFAULT_CATALOG=[{"id":"obarros-especial","category":"salgadas","tag":"SALGADA","name":"D'barros Especial","desc":"Muçarela, carne seca desfiada, cubos dourados e toque da casa.","image":"assets/custom/pizza-especial.webp","sizes":[["P",39.9],["M",49.9],["G",59.9]],"active":true,"promoActive":false,"promoPct":0},{"id":"calabresa","category":"salgadas","tag":"SALGADA","name":"Calabresa Crocante","desc":"Calabresa, queijo, cebola e cobertura gratinada.","image":"assets/custom/pizza-calabresa.webp","sizes":[["P",36.9],["M",45.9],["G",54.9]],"active":true,"promoActive":true,"promoPct":10},{"id":"frango","category":"salgadas","tag":"SALGADA","name":"Frango Cremoso","desc":"Frango desfiado, creme especial e bastante queijo.","image":"assets/custom/pizza-frango.webp","sizes":[["P",38.9],["M",47.9],["G",57.9]],"active":true,"promoActive":false,"promoPct":0},{"id":"branca","category":"salgadas","tag":"SALGADA","name":"Branca Especial","desc":"Massa alta, queijo marcante e finalização com ervas.","image":"assets/custom/pizza-branca.webp","sizes":[["P",37.9],["M",46.9],["G",56.9]],"active":true,"promoActive":false,"promoPct":0},{"id":"doce-casa","category":"doces","tag":"DOCE","name":"Doce da Casa","desc":"Base doce com calda cremosa e acabamento marcante.","image":"assets/custom/pizza-doce-caramelo.webp","sizes":[["M",37.9],["G",44.9]],"active":true,"promoActive":false,"promoPct":0},{"id":"choco","category":"doces","tag":"DOCE","name":"Choco D'barros","desc":"Chocolate e doce de leite em uma pizza de sobremesa.","image":"assets/custom/pizza-doce-chocolate.webp","sizes":[["M",39.9],["G",47.9]],"active":true,"promoActive":false,"promoPct":0},{"id":"combo-casal","category":"combos","tag":"COMBO","name":"Combo Casal","desc":"1 pizza salgada + 1 pizza doce + refrigerante.","image":"assets/custom/banner.webp","fixedPrice":89.9,"active":true,"promoActive":true,"promoPct":8},{"id":"guarana","category":"bebidas","tag":"BEBIDA","name":"Guaraná 600ml","desc":"Bebida gelada para completar o pedido.","image":"assets/custom/about.webp","fixedPrice":7.9,"active":true,"promoActive":false,"promoPct":0}];
const DEFAULT_DELIVERY={"anotaUrl":"","featuredProductId":"obarros-especial","showcaseIds":["obarros-especial","calabresa","frango","doce-casa"],"showcaseCount":4,"promoDayActive":true,"promoDayProductId":"calabresa","promoDayTitle":"Promoção do dia","promoDayText":"Pizza selecionada com preço especial hoje.","promoDayPrice":"R$ 49,90"};
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
function base(p){return p.fixedPrice??p.sizes?.[0]?.[1]??0}
function sale(p){const b=base(p);return p.promoActive&&p.promoPct?b*(1-p.promoPct/100):b}
function clone(v){return JSON.parse(JSON.stringify(v))}
function readLocal(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));if(v)return v}catch(e){}const boot=window.DBARROS_BOOTSTRAP||{};if(key===CATALOG_KEY&&Array.isArray(boot.catalog))return clone(boot.catalog);if(key===DELIVERY_KEY&&boot.delivery)return clone(boot.delivery);return clone(fallback)}
function showMissingLink(){const t=document.getElementById('toast');if(t){t.hidden=false;setTimeout(()=>t.hidden=true,2400)}}
function bindAnota(url){document.querySelectorAll('[data-anota-link]').forEach(a=>{if(url){a.href=url;a.target='_blank';a.rel='noopener'}else{a.href='#';a.onclick=e=>{e.preventDefault();showMissingLink()}}})}
function renderStorefront(){
 const catalog=readLocal(CATALOG_KEY,DEFAULT_CATALOG).filter(p=>p.active!==false);
 const settings={...DEFAULT_DELIVERY,...readLocal(DELIVERY_KEY,DEFAULT_DELIVERY)};
 const anota=settings.anotaUrl||''; bindAnota(anota); const featured=catalog.find(p=>p.id===settings.featuredProductId)||catalog[0];
 const fimg=document.getElementById('featuredImage'),fname=document.getElementById('featuredName'),fdesc=document.getElementById('featuredDesc');
 if(featured){if(fimg)fimg.src=featured.image;if(fname)fname.textContent=featured.name;if(fdesc)fdesc.textContent=featured.desc||''}
 const promo=catalog.find(p=>p.id===settings.promoDayProductId)||catalog.find(p=>p.promoActive)||featured;
 const pcard=document.getElementById('promoVisualCard');if(pcard)pcard.style.display=settings.promoDayActive===false?'none':'block';
 if(promo){const im=document.getElementById('promoVisualImage'),ti=document.getElementById('promoVisualTitle'),tx=document.getElementById('promoVisualText'),pr=document.getElementById('promoVisualPrice');if(im)im.src=promo.image;if(ti)ti.textContent=settings.promoDayTitle||promo.name;if(tx)tx.textContent=settings.promoDayText||promo.desc||'Oferta especial do dia.';if(pr)pr.textContent=settings.promoDayPrice||money.format(sale(promo))}
 let ids=(settings.showcaseIds||[]).filter(id=>catalog.some(p=>p.id===id));if(!ids.length)ids=catalog.map(p=>p.id);
 const products=ids.slice(0,Math.max(1,Number(settings.showcaseCount||4))).map(id=>catalog.find(p=>p.id===id)).filter(Boolean);
 const box=document.getElementById('deliveryProducts');
 if(box){box.innerHTML=products.length?products.map(p=>`<article class="product-card"><div class="product-media"><img src="${p.image}" alt="${p.name}">${p.promoActive?`<span class="promo-badge product-promo-badge">PROMO -${p.promoPct}%</span>`:``}</div><div class="product-body"><small>${p.tag||''}</small><h3>${p.name}</h3><p>${p.desc||''}</p><div class="price-line">${p.promoActive?`<del>${money.format(base(p))}</del>`:''}<strong>${money.format(sale(p))}</strong></div><a href="${anota||'#'}" ${anota?'target="_blank" rel="noopener"':''} data-product-link>Pedir este sabor →</a></div></article>`).join(''):`<div class="store-empty">Nenhum item selecionado para a vitrine.</div>`;if(!anota)box.querySelectorAll('[data-product-link]').forEach(a=>a.onclick=e=>{e.preventDefault();showMissingLink()})}
}
document.addEventListener('DOMContentLoaded',renderStorefront);window.addEventListener('storage',renderStorefront);


async function loadStoredHeroVideo(){try{const r=indexedDB.open('dbarros_media_v1',1);const db=await new Promise((resolve,reject)=>{r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('media'))r.result.createObjectStore('media')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const blob=await new Promise((resolve,reject)=>{const q=db.transaction('media','readonly').objectStore('media').get('heroVideo');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});if(!blob)return;const video=document.getElementById('heroBackgroundVideo'),source=document.getElementById('heroBackgroundSource');if(video&&source){source.src=URL.createObjectURL(blob);video.load();video.play().catch(()=>{})}}catch(e){}}
document.addEventListener('DOMContentLoaded',loadStoredHeroVideo);

