const API_BASE=(window.DBARROS_BASE_PATH||"")+"/api";
const DEFAULT_CATALOG=[{"id": "obarros-especial", "category": "salgadas", "tag": "SALGADA", "name": "D'barros Especial", "desc": "Muçarela, carne seca desfiada, cubos dourados e toque da casa.", "image": "assets/custom/pizza-especial.webp", "sizes": [["P", 39.9], ["M", 49.9], ["G", 59.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "calabresa", "category": "salgadas", "tag": "SALGADA", "name": "Calabresa Crocante", "desc": "Calabresa, queijo, cebola e cobertura gratinada.", "image": "assets/custom/pizza-calabresa.webp", "sizes": [["P", 36.9], ["M", 45.9], ["G", 54.9]], "active": true, "promoActive": true, "promoPct": 10}, {"id": "frango", "category": "salgadas", "tag": "SALGADA", "name": "Frango Cremoso", "desc": "Frango desfiado, creme especial e bastante queijo.", "image": "assets/custom/pizza-frango.webp", "sizes": [["P", 38.9], ["M", 47.9], ["G", 57.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "branca", "category": "salgadas", "tag": "SALGADA", "name": "Branca Especial", "desc": "Massa alta, queijo marcante e finalização com ervas.", "image": "assets/custom/pizza-branca.webp", "sizes": [["P", 37.9], ["M", 46.9], ["G", 56.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "doce-casa", "category": "doces", "tag": "DOCE", "name": "Doce da Casa", "desc": "Base doce com calda cremosa e acabamento marcante.", "image": "assets/custom/pizza-doce-caramelo.webp", "sizes": [["M", 37.9], ["G", 44.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "choco", "category": "doces", "tag": "DOCE", "name": "Choco D'barros", "desc": "Chocolate e doce de leite em uma pizza de sobremesa.", "image": "assets/custom/pizza-doce-chocolate.webp", "sizes": [["M", 39.9], ["G", 47.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "combo-casal", "category": "combos", "tag": "COMBO", "name": "Combo Casal", "desc": "1 pizza salgada + 1 pizza doce + refrigerante.", "image": "assets/custom/banner.webp", "fixedPrice": 89.9, "active": true, "promoActive": true, "promoPct": 8}, {"id": "guarana", "category": "bebidas", "tag": "BEBIDA", "name": "Guaraná 600ml", "desc": "Bebida gelada para completar o pedido.", "image": "assets/custom/about.webp", "fixedPrice": 7.9, "active": true, "promoActive": false, "promoPct": 0}];
const DEFAULT_DELIVERY={"anotaUrl": "", "featuredProductId": "obarros-especial", "showcaseIds": ["obarros-especial", "calabresa", "frango", "doce-casa"], "showcaseCount": 4, "promoDayActive": true, "promoDayProductId": "calabresa", "promoDayTitle": "Promoção do dia", "promoDayText": "Pizza selecionada com preço especial hoje.", "promoDayPrice": "R$ 49,90"};
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
function base(p){return p.fixedPrice??p.sizes?.[0]?.[1]??0}
function sale(p){const b=base(p);return p.promoActive&&p.promoPct?b*(1-p.promoPct/100):b}
async function getJson(url,fallback){try{const r=await fetch(url,{cache:'no-store'});if(r.ok)return await r.json()}catch(e){}return fallback}
function showMissingLink(){const t=document.getElementById('toast');if(t){t.hidden=false;setTimeout(()=>t.hidden=true,2400)}}
async function init(){
  const [catalogRaw,settingsRaw]=await Promise.all([getJson(`${API_BASE}/catalog.php`,DEFAULT_CATALOG),getJson(`${API_BASE}/delivery.php`,DEFAULT_DELIVERY)]);
  const catalog=(Array.isArray(catalogRaw)?catalogRaw:DEFAULT_CATALOG).filter(p=>p.active!==false);
  const settings={...DEFAULT_DELIVERY,...(settingsRaw||{})};
  const anota=settings.anotaUrl||'';
  document.querySelectorAll('[data-anota-link]').forEach(a=>{if(anota){a.href=anota;a.target='_blank';a.rel='noopener'}else{a.href='#';a.addEventListener('click',e=>{e.preventDefault();showMissingLink()})}});
  const f=catalog.find(p=>p.id===settings.featuredProductId)||catalog[0];
  if(f){document.getElementById('featuredImage').src=f.image;document.getElementById('featuredName').textContent=f.name;document.getElementById('featuredDesc').textContent=f.desc||''}
  const sq=document.getElementById('promoDaySquare');
  if(sq) sq.style.display=settings.promoDayActive?'flex':'none';
  if(document.getElementById('promoDayTitle'))document.getElementById('promoDayTitle').textContent=settings.promoDayTitle||'Promoção do dia';
  if(document.getElementById('promoDayPrice'))document.getElementById('promoDayPrice').textContent=settings.promoDayPrice||'Oferta especial';
  if(document.getElementById('promoDayText'))document.getElementById('promoDayText').textContent=settings.promoDayText||'';
  let ids=(settings.showcaseIds||[]).filter(id=>catalog.some(p=>p.id===id));if(!ids.length)ids=catalog.map(p=>p.id);
  const products=ids.slice(0,Number(settings.showcaseCount||4)).map(id=>catalog.find(p=>p.id===id)).filter(Boolean);
  const box=document.getElementById('deliveryProducts');if(box)box.innerHTML=products.map(p=>`<article class="product-card"><img src="${p.image}" alt="${p.name}"><div class="product-body">${p.promoActive?`<span class="promo-badge">PROMO -${p.promoPct}%</span>`:`<small>${p.tag}</small>`}<h3>${p.name}</h3><p>${p.desc||''}</p><div class="price-line">${p.promoActive?`<del>${money.format(base(p))}</del>`:''}<strong>${money.format(sale(p))}</strong></div><a href="${anota||'#'}" ${anota?'target="_blank" rel="noopener"':''}>Pedir este sabor →</a></div></article>`).join('');
}
init();
