const CATALOG_KEY="dbarros_catalog_v3"; const DELIVERY_KEY="dbarros_delivery_site_v2"; const API_BASE=(window.DBARROS_BASE_PATH||"")+"/api";
const DEFAULT_CATALOG=[{"id": "obarros-especial", "category": "salgadas", "tag": "SALGADA", "name": "D'barros Especial", "desc": "Muçarela, carne seca desfiada, cubos dourados e toque da casa.", "image": "assets/custom/pizza-especial.webp", "sizes": [["P", 39.9], ["M", 49.9], ["G", 59.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "calabresa", "category": "salgadas", "tag": "SALGADA", "name": "Calabresa Crocante", "desc": "Calabresa, queijo, cebola e cobertura gratinada.", "image": "assets/custom/pizza-calabresa.webp", "sizes": [["P", 36.9], ["M", 45.9], ["G", 54.9]], "active": true, "promoActive": true, "promoPct": 10}, {"id": "frango", "category": "salgadas", "tag": "SALGADA", "name": "Frango Cremoso", "desc": "Frango desfiado, creme especial e bastante queijo.", "image": "assets/custom/pizza-frango.webp", "sizes": [["P", 38.9], ["M", 47.9], ["G", 57.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "branca", "category": "salgadas", "tag": "SALGADA", "name": "Branca Especial", "desc": "Massa alta, queijo marcante e finalização com ervas.", "image": "assets/custom/pizza-branca.webp", "sizes": [["P", 37.9], ["M", 46.9], ["G", 56.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "doce-casa", "category": "doces", "tag": "DOCE", "name": "Doce da Casa", "desc": "Base doce com calda cremosa e acabamento marcante.", "image": "assets/custom/pizza-doce-caramelo.webp", "sizes": [["M", 37.9], ["G", 44.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "choco", "category": "doces", "tag": "DOCE", "name": "Choco D'barros", "desc": "Chocolate e doce de leite em uma pizza de sobremesa.", "image": "assets/custom/pizza-doce-chocolate.webp", "sizes": [["M", 39.9], ["G", 47.9]], "active": true, "promoActive": false, "promoPct": 0}, {"id": "combo-casal", "category": "combos", "tag": "COMBO", "name": "Combo Casal", "desc": "1 pizza salgada + 1 pizza doce + refrigerante.", "image": "assets/custom/banner.webp", "fixedPrice": 89.9, "active": true, "promoActive": true, "promoPct": 8}, {"id": "guarana", "category": "bebidas", "tag": "BEBIDA", "name": "Guaraná 600ml", "desc": "Bebida gelada para completar o pedido.", "image": "assets/custom/about.webp", "fixedPrice": 7.9, "active": true, "promoActive": false, "promoPct": 0}];
const DEFAULT_DELIVERY={"anotaUrl": "", "featuredProductId": "obarros-especial", "showcaseIds": ["obarros-especial", "calabresa", "frango", "doce-casa"], "showcaseCount": 4, "promoDayActive": true, "promoDayProductId": "calabresa", "promoDayTitle": "Promoção do dia", "promoDayText": "Pizza selecionada com preço especial hoje.", "promoDayPrice": "R$ 49,90"};
const TABLES=[
{n:'01',status:'busy',time:'42 min',total:126.50,items:[['1x',"D'barros Especial G",'Borda Catupiry',67.90],['1x','Guaraná 600ml','',7.90],['1x','Doce da Casa M','',50.70]]},{n:'02',status:'free',time:'',total:0,items:[]},{n:'03',status:'busy',time:'28 min',total:89.90,items:[['1x','Calabresa G','',54.90],['1x','Bebidas','',35.00]]},{n:'04',status:'busy',time:'17 min',total:74.80,items:[['1x','Frango Cremoso M','',47.90],['2x','Guaraná 600ml','',15.80],['1x','Água','',11.10]]},{n:'05',status:'busy',time:'51 min',total:158.40,items:[['2x',"D'barros Especial G",'',119.80],['1x','Doce da Casa','',38.60]]},{n:'06',status:'free',time:'',total:0,items:[]},{n:'07',status:'busy',time:'23 min',total:112.70,items:[['1x',"D'barros Especial G",'Borda Catupiry · sem cebola',67.90],['2x','Guaraná 600ml','',15.80],['1x','Doce da Casa M','',29.00]]},{n:'08',status:'busy',time:'12 min',total:83.90,items:[['1x','Branca Especial G','',56.90],['1x','Suco','',27.00]]},{n:'09',status:'bill',time:'1h 08',total:96.00,items:[['1x','Calabresa G','',54.90],['1x','Doce','',33.20],['1x','Bebida','',7.90]]},{n:'10',status:'busy',time:'8 min',total:72.70,items:[['1x','Frango Cremoso M','',47.90],['1x','Bebidas','',24.80]]}];
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const grid=document.getElementById('tablesGrid'); const tableModal=document.getElementById('tableModal'); const cashModal=document.getElementById('cashModal'); const toast=document.getElementById('toast');
let selectedTable=null, selectedPayment='PIX', nextOrder=2418, dayClosed=false, editId=null, catalogSearch='', catalogCategory='all';
let catalog=loadJson(CATALOG_KEY,DEFAULT_CATALOG), delivery=loadJson(DELIVERY_KEY,DEFAULT_DELIVERY); const cash={money:985.70,pix:1516.00,card:1341.00};
function loadJson(k,f){const b=window.DBARROS_BOOTSTRAP||{};if(k===CATALOG_KEY&&Array.isArray(b.catalog))return JSON.parse(JSON.stringify(b.catalog));if(k===DELIVERY_KEY&&b.delivery)return JSON.parse(JSON.stringify(b.delivery));try{const v=JSON.parse(localStorage.getItem(k));if(v)return v}catch(e){}return JSON.parse(JSON.stringify(f))}
function showToast(t){toast.textContent=t;toast.hidden=false;setTimeout(()=>toast.hidden=true,2400)} async function apiSave(file,data){
  if(window.DBARROS_BOOTSTRAP?.demoMode){
    try{localStorage.setItem(file==='catalog.php'?CATALOG_KEY:DELIVERY_KEY,JSON.stringify(data))}catch(e){}
    showToast('Alteração aplicada apenas na demonstração.');
    return true;
  }
  try{
    const r=await fetch(`${API_BASE}/${file}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
    if(!r.ok)throw new Error('save');
    return true;
  }catch(e){showToast('Falha ao salvar no servidor.');return false}
} function saveCatalog(){renderCatalog();renderDeliveryAdmin();apiSave('catalog.php',catalog)} function saveDelivery(){apiSave('delivery.php',delivery)}
function slugify(t){return t.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,42)||'produto'} function parseMoney(v){if(!v)return null;const n=Number(String(v).replace(/\./g,'').replace(',','.'));return Number.isFinite(n)&&n>=0?n:null} function fmt(v){return v==null?'':Number(v).toFixed(2).replace('.',',')} function basePrice(p){return p.fixedPrice??p.sizes?.[0]?.[1]??0} function displayPrice(p){const b=basePrice(p);return p.promoActive&&p.promoPct?b*(1-p.promoPct/100):b}
function renderTables(){grid.innerHTML=TABLES.map(t=>{const label=t.status==='free'?'Livre':t.status==='bill'?'Fechar mesa':'Em consumo', action=t.status==='bill'?'Fechar agora':'Ver consumo';return `<article class="table-card ${t.status}"><div class="table-top"><span class="table-number">${t.n}</span><span class="table-status">${label}</span></div>${t.status==='free'?'<small>Disponível</small><strong>-</strong>':`<small>${t.time} · ${t.items.length} itens</small><strong>${brl.format(t.total)}</strong>`}<button data-table="${t.n}">${action}</button></article>`}).join('');const open=TABLES.filter(t=>t.status!=='free');document.getElementById('occupiedTables').textContent=open.length;document.getElementById('openTablesNote').textContent=open.length?`${open.length} mesa${open.length===1?'':'s'} ainda aberta${open.length===1?'':'s'}`:'Todas as mesas foram fechadas';updateCash();updateCloseDayState()}
function openTable(n){if(dayClosed)return showToast('O dia já foi encerrado.');const t=TABLES.find(x=>x.n===n);if(!t||t.status==='free')return;selectedTable=t;document.getElementById('modalTableNumber').textContent=t.n;document.getElementById('modalOrderList').innerHTML=t.items.map(i=>`<div class="order-line"><span>${i[0]}</span><div>${i[1]}${i[2]?`<small>${i[2]}</small>`:''}</div><b>${brl.format(i[3])}</b></div>`).join('');document.getElementById('modalTableTotal').textContent=brl.format(t.total);tableModal.hidden=false}
grid.addEventListener('click',e=>{const n=e.target.closest('[data-table]')?.dataset.table;if(n)openTable(n)});document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',()=>tableModal.hidden=true));document.querySelectorAll('[data-close-cash]').forEach(el=>el.addEventListener('click',()=>cashModal.hidden=true));document.querySelectorAll('.payment').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.payment').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedPayment=btn.dataset.payment}));
function openTablesTotal(){return TABLES.filter(t=>t.status!=='free').reduce((s,t)=>s+t.total,0)} function receivedTotal(){return cash.money+cash.pix+cash.card} function updateCash(){document.getElementById('cashMoney').textContent=brl.format(cash.money);document.getElementById('cashPix').textContent=brl.format(cash.pix);document.getElementById('cashCard').textContent=brl.format(cash.card);document.getElementById('cashReceived').textContent=brl.format(receivedTotal());document.getElementById('openTablesValue').textContent=brl.format(openTablesTotal());document.getElementById('closeMoney').textContent=brl.format(cash.money);document.getElementById('closePix').textContent=brl.format(cash.pix);document.getElementById('closeCard').textContent=brl.format(cash.card);document.getElementById('closeTotal').textContent=brl.format(receivedTotal());document.getElementById('salesToday').textContent=brl.format(receivedTotal())}
function updateCloseDayState(){const n=TABLES.filter(t=>t.status!=='free').length,b=document.getElementById('closeCashButton'),r=document.getElementById('dayCloseRule'),tx=document.getElementById('dayCloseRuleText');if(dayClosed){b.disabled=true;b.textContent='Dia fechado';r.classList.add('ready');tx.textContent='Operação encerrada. Caixa fechado.';return} if(n===0){b.disabled=false;b.textContent='Fechar dia';r.classList.add('ready');tx.textContent='Todas as mesas estão fechadas. O dia pode ser encerrado.'}else{b.disabled=true;b.textContent=`Fechar dia (${n} abertas)`;r.classList.remove('ready');tx.textContent=`Faltam fechar ${n} mesa${n===1?'':'s'} antes do fechamento do dia.`}}
document.getElementById('finishTableButton').addEventListener('click',()=>{if(!selectedTable||dayClosed)return;const v=selectedTable.total;if(selectedPayment==='PIX')cash.pix+=v;if(selectedPayment==='Cartão')cash.card+=v;if(selectedPayment==='Dinheiro')cash.money+=v;showToast(`Mesa ${selectedTable.n} fechada em ${selectedPayment} · ${brl.format(v)}`);selectedTable.status='free';selectedTable.time='';selectedTable.total=0;selectedTable.items=[];tableModal.hidden=true;renderTables()});
document.getElementById('closeCashButton').addEventListener('click',()=>{if(TABLES.some(t=>t.status!=='free'))return showToast('Feche todas as mesas antes de encerrar o dia.');cashModal.hidden=false});document.getElementById('confirmCloseDay').addEventListener('click',()=>{if(TABLES.some(t=>t.status!=='free'))return;dayClosed=true;cashModal.hidden=true;const s=document.querySelector('.cash-open');s.textContent=`DIA FECHADO · ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`;s.classList.add('closed');document.getElementById('simulateOrder').disabled=true;const d=document.createElement('div');d.className='day-closed-banner';d.innerHTML=`<strong>✓ Dia encerrado com sucesso</strong><span>Total recebido: ${brl.format(receivedTotal())}</span>`;document.querySelector('.cash-main').appendChild(d);updateCloseDayState();showToast('Dia e caixa encerrados.')});
function addQueueRow(order,table){const q=document.getElementById('printQueue'),r=document.createElement('div');r.className='queue-row printing';r.innerHTML=`<span>#${order}</span><b>Mesa ${table}</b><small>Enviando...</small>`;q.prepend(r);while(q.children.length>4)q.lastElementChild.remove();return r} document.getElementById('simulateOrder').addEventListener('click',()=>{if(dayClosed)return;const order=nextOrder++,table=['01','03','05','07','08','10'][Math.floor(Math.random()*6)],row=addQueueRow(order,table),paper=document.getElementById('printerPaper'),printer=document.getElementById('printerIcon');document.getElementById('lastPrint').textContent=`Pedido #${order} · Mesa ${table}`;document.getElementById('lastPrintStatus').textContent='Enviando para COZINHA-01...';paper.innerHTML=`<b>D'BARROS</b><span>COMANDA</span><strong>#${order} · MESA ${table}</strong>`;paper.classList.remove('printing');void paper.offsetWidth;paper.classList.add('printing');printer.animate([{transform:'translateX(0)'},{transform:'translateX(-2px)'},{transform:'translateX(2px)'},{transform:'translateX(0)'}],{duration:220,iterations:2});setTimeout(()=>row.querySelector('small').textContent='Imprimindo...',650);setTimeout(()=>{row.className='queue-row printed';row.querySelector('small').textContent='Impresso';document.getElementById('lastPrintStatus').textContent='✓ Impresso agora';paper.classList.remove('printing');showToast(`Comanda #${order} impressa na COZINHA-01`)},1800)});
function renderCatalog(){const list=document.getElementById('catalogList'),f=catalog.filter(p=>{const cat=catalogCategory==='all'||p.category===catalogCategory,txt=`${p.name} ${p.desc||''}`.toLowerCase();return cat&&(!catalogSearch||txt.includes(catalogSearch))});list.innerHTML=f.map(p=>`<div class="catalog-row"><img src="${p.image}" alt=""><div class="catalog-name"><strong>${p.name}</strong><small>${p.category}</small></div><div class="catalog-price"><b>${brl.format(displayPrice(p))}</b>${p.sizes?p.sizes.map(s=>`${s[0]} ${brl.format(s[1])}`).join(' · '):'Preço único'}</div><span class="catalog-promo ${p.promoActive?'':'off'}">${p.promoActive?`-${p.promoPct}%`:'Sem promo'}</span><button class="catalog-edit" data-edit-product="${p.id}">Editar</button></div>`).join('')}
function resetEditor(){editId=null;document.getElementById('editorTitle').textContent='Novo item';['productId','productName','productDesc','priceP','priceM','priceG','fixedPrice','promoPct'].forEach(id=>document.getElementById(id).value='');document.getElementById('productCategory').value='salgadas';document.getElementById('productActive').value='true';document.getElementById('promoActive').checked=false;document.getElementById('productImage').value='assets/custom/pizza-especial.webp';document.getElementById('deleteProductButton').hidden=true}
function editProduct(id){const p=catalog.find(x=>x.id===id);if(!p)return;editId=id;document.getElementById('editorTitle').textContent='Editar item';document.getElementById('productName').value=p.name;document.getElementById('productCategory').value=p.category;document.getElementById('productActive').value=String(p.active!==false);document.getElementById('productDesc').value=p.desc||'';const m=Object.fromEntries((p.sizes||[]).map(s=>s));document.getElementById('priceP').value=fmt(m.P);document.getElementById('priceM').value=fmt(m.M);document.getElementById('priceG').value=fmt(m.G);document.getElementById('fixedPrice').value=fmt(p.fixedPrice);document.getElementById('promoActive').checked=!!p.promoActive;document.getElementById('promoPct').value=p.promoPct||'';document.getElementById('productImage').value=p.image;document.getElementById('deleteProductButton').hidden=false}
document.getElementById('catalogSearch').addEventListener('input',e=>{catalogSearch=e.target.value.trim().toLowerCase();renderCatalog()});document.getElementById('catalogCategoryFilter').addEventListener('change',e=>{catalogCategory=e.target.value;renderCatalog()});document.getElementById('catalogList').addEventListener('click',e=>{const id=e.target.closest('[data-edit-product]')?.dataset.editProduct;if(id)editProduct(id)});document.getElementById('newProductButton').addEventListener('click',resetEditor);document.getElementById('cancelEditButton').addEventListener('click',resetEditor);
document.getElementById('productForm').addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('productName').value.trim();if(!name)return showToast('Informe o nome.');const pm={P:parseMoney(document.getElementById('priceP').value),M:parseMoney(document.getElementById('priceM').value),G:parseMoney(document.getElementById('priceG').value)},fixed=parseMoney(document.getElementById('fixedPrice').value),sizes=Object.entries(pm).filter(([,v])=>v!=null);if(fixed==null&&!sizes.length)return showToast('Informe ao menos um preço.');const category=document.getElementById('productCategory').value,pct=Math.max(0,Math.min(90,Number(document.getElementById('promoPct').value||0)));const obj={id:editId||`${slugify(name)}-${Date.now().toString().slice(-5)}`,name,category,tag:{salgadas:'SALGADA',doces:'DOCE',combos:'COMBO',bebidas:'BEBIDA'}[category],desc:document.getElementById('productDesc').value.trim(),image:document.getElementById('productImage').value,active:document.getElementById('productActive').value==='true',promoActive:document.getElementById('promoActive').checked&&pct>0,promoPct:pct};if(fixed!=null)obj.fixedPrice=fixed;else obj.sizes=sizes;if(editId)catalog[catalog.findIndex(p=>p.id===editId)]=obj;else catalog.push(obj);saveCatalog();resetEditor();showToast(`${name} salvo no cardápio.`)});document.getElementById('deleteProductButton').addEventListener('click',()=>{if(!editId)return;const p=catalog.find(x=>x.id===editId);if(p&&confirm(`Excluir "${p.name}"?`)){catalog=catalog.filter(x=>x.id!==editId);saveCatalog();resetEditor();showToast('Item excluído.')}});
function renderDeliveryAdmin(){const a=catalog.filter(p=>p.active!==false),opts=a.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');document.getElementById('featuredProduct').innerHTML=opts;document.getElementById('promoDayProduct').innerHTML=opts;document.getElementById('featuredProduct').value=delivery.featuredProductId||a[0]?.id||'';document.getElementById('promoDayProduct').value=delivery.promoDayProductId||a[0]?.id||'';document.getElementById('anotaUrl').value=delivery.anotaUrl||'';document.getElementById('showcaseCount').value=String(delivery.showcaseCount||4);document.getElementById('promoDayActive').checked=!!delivery.promoDayActive;document.getElementById('promoDayTitle').value=delivery.promoDayTitle||'';document.getElementById('promoDayText').value=delivery.promoDayText||'';document.getElementById('promoDayPrice').value=delivery.promoDayPrice||'';document.getElementById('deliveryProductsPicker').innerHTML=a.map(p=>`<label class="delivery-pick-item"><input type="checkbox" value="${p.id}" ${delivery.showcaseIds?.includes(p.id)?'checked':''}><span>${p.name}</span></label>`).join('');updateDeliveryPreview()}
function updateDeliveryPreview(){const f=catalog.find(p=>p.id===document.getElementById('featuredProduct').value)||catalog[0],promo=catalog.find(p=>p.id===document.getElementById('promoDayProduct').value)||f;if(f){document.getElementById('previewFeaturedImage').src=f.image;document.getElementById('previewFeaturedName').textContent=f.name;document.getElementById('previewFeaturedDesc').textContent=f.desc||''} const box=document.getElementById('previewPromo');box.style.display=document.getElementById('promoDayActive').checked?'block':'none';document.getElementById('previewPromoTitle').textContent=document.getElementById('promoDayTitle').value||promo?.name||'Promoção do dia';document.getElementById('previewPromoPrice').textContent=document.getElementById('promoDayPrice').value||'Oferta especial'}
['featuredProduct','promoDayProduct','promoDayActive','promoDayTitle','promoDayPrice'].forEach(id=>document.getElementById(id).addEventListener('input',updateDeliveryPreview));document.getElementById('deliverySiteForm').addEventListener('submit',e=>{e.preventDefault();delivery={anotaUrl:document.getElementById('anotaUrl').value.trim(),featuredProductId:document.getElementById('featuredProduct').value,showcaseIds:Array.from(document.querySelectorAll('#deliveryProductsPicker input:checked')).map(i=>i.value),showcaseCount:Number(document.getElementById('showcaseCount').value||4),promoDayActive:document.getElementById('promoDayActive').checked,promoDayProductId:document.getElementById('promoDayProduct').value,promoDayTitle:document.getElementById('promoDayTitle').value.trim(),promoDayText:document.getElementById('promoDayText').value.trim(),promoDayPrice:document.getElementById('promoDayPrice').value.trim()};saveDelivery();showToast('Site de delivery atualizado.')});
renderTables();renderCatalog();resetEditor();renderDeliveryAdmin();
if(window.DBARROS_BOOTSTRAP?.demoMode){
  document.body.classList.add('investor-demo-mode');
  const bar=document.createElement('div');
  bar.className='investor-demo-banner';
  bar.innerHTML='<b>MODO INVESTIDOR</b><span>Dados de demonstração · alterações não afetam a operação real</span>';
  document.body.appendChild(bar);

  document.querySelectorAll('a[href*="/gestor/qrs"]').forEach(a=>{
    a.href=(window.DBARROS_BASE_PATH||".")+"/qrs-mesas.html";
  });
  document.querySelectorAll('a[href*="/gestor/comanda"]').forEach(a=>{
    a.href=(window.DBARROS_BASE_PATH||".")+"/comanda-exemplo-80mm.pdf";
  });
  document.querySelectorAll('a[href="salao.html?mesa=01"]').forEach(a=>{
    a.href=(window.DBARROS_BASE_PATH||".")+"/demo-salao.html";
  });
  document.querySelectorAll('a[href="index.html"]').forEach(a=>{
    a.href=(window.DBARROS_BASE_PATH||".")+"/demo-site.html";
  });
}
