<?php
require __DIR__.'/../lib/bootstrap.php';require_admin();$pageTitle='Portaria / QR';
$error='';
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['undo_id'])){
    verify_csrf();
    try{undo_ticket_checkin((int)$_POST['undo_id'],(int)(admin_user()['id']??0));flash('success','Check-in desfeito. O ingresso voltou a ficar válido.');redirect('checkin.php');}
    catch(Throwable $e){$error=$e->getMessage();}
}
$history=db()->query("SELECT l.*,t.status,t.checked_in_at,o.buyer_name,e.title event_title,oi.ticket_name,a.name admin_name FROM checkin_logs l JOIN tickets t ON t.id=l.ticket_id JOIN orders o ON o.id=t.order_id JOIN order_items oi ON oi.id=t.order_item_id JOIN events e ON e.id=o.event_id LEFT JOIN admins a ON a.id=l.admin_id ORDER BY l.id DESC LIMIT 80")->fetchAll();
require '_header.php';?>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="scan-layout">
  <section class="admin-card"><div class="card-head"><div><h2>Ler ingresso</h2><p>Aponte a câmera para o QR Code ou use a leitura manual.</p></div></div>
    <div class="scan-camera"><div class="scan-video-wrap" id="native-reader"><video id="scan-video" playsinline muted></video><div class="scan-frame"></div><div id="camera-note">Clique em “Ativar câmera”.</div></div><div id="html5-reader" style="display:none;background:#fff;border-radius:18px;overflow:hidden"></div>
      <div class="scan-actions"><button type="button" class="btn btn-primary btn-small" id="start-camera">Ativar câmera</button><button type="button" class="btn btn-ghost btn-small" id="stop-camera">Parar</button><label class="btn btn-ghost btn-small" style="cursor:pointer">Ler foto<input type="file" id="qr-photo" accept="image/*" hidden></label></div>
    </div>
    <form class="scan-manual" id="manual-form"><input id="manual-code" placeholder="TF-... ou payload do QR" autocomplete="off"><button class="btn btn-secondary" type="submit">Validar código</button></form>
  </section>
  <aside class="scan-result" id="scan-result"><span class="eyebrow dark">RESULTADO</span><h2>Aguardando leitura</h2><p>O resultado aparecerá aqui. Leituras duplicadas são bloqueadas no servidor.</p></aside>
</div>
<div class="admin-card"><div class="card-head"><div><h2>Histórico da portaria</h2><p>Últimas leituras e reversões.</p></div></div><div class="table-wrap"><table class="scan-history"><thead><tr><th>Horário</th><th>Ação</th><th>Ingresso</th><th>Evento</th><th>Cliente</th><th>Equipe</th><th></th></tr></thead><tbody><?php foreach($history as $h):?><tr><td><?=e(dt_db_br($h['created_at']))?></td><td><span class="scan-status-dot <?=$h['action']==='checkin'?'ok':''?>"></span><?=e($h['action']==='checkin'?'Entrada':'Desfeito')?></td><td><code><?=e($h['ticket_code'])?></code><br><small><?=e($h['ticket_name'])?></small></td><td><?=e($h['event_title'])?></td><td><?=e($h['buyer_name'])?></td><td><?=e($h['admin_name']??'—')?></td><td><?php if($h['action']==='checkin' && $h['status']==='used'):?><form method="post" onsubmit="return confirm('Desfazer este check-in?')"><?=csrf_field()?><input type="hidden" name="undo_id" value="<?=intval($h['ticket_id'])?>"><button class="btn btn-small btn-ghost dark-outline">Desfazer</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$history):?><tr><td colspan="7">Nenhuma leitura ainda.</td></tr><?php endif;?></tbody></table></div></div>
<script>
const csrf=<?=json_encode(csrf_token())?>;let stream=null,active=false,lastValue='',lastAt=0,detector=null,h5=null;
const video=document.getElementById('scan-video'),note=document.getElementById('camera-note'),result=document.getElementById('scan-result');
function showResult(data){result.className='scan-result '+(data.ok?'ok':'error');let t=data.ticket||{};result.innerHTML=`<span class="eyebrow dark">${data.ok?'ENTRADA LIBERADA':'ATENÇÃO'}</span><h2>${escapeHtml(data.message||'')}</h2>${t.code?`<p><b>${escapeHtml(t.buyer_name||'')}</b><br>${escapeHtml(t.ticket_name||'')}<br>${escapeHtml(t.event_title||'')}<br><code>${escapeHtml(t.code)}</code></p>`:''}`;if(data.ok){try{navigator.vibrate&&navigator.vibrate(120)}catch(e){}}}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
async function sendCode(code){code=(code||'').trim();if(!code)return;const now=Date.now();if(code===lastValue&&now-lastAt<3500)return;lastValue=code;lastAt=now;const fd=new FormData();fd.append('csrf',csrf);fd.append('code',code);try{const r=await fetch('checkin-api.php',{method:'POST',body:fd,credentials:'same-origin'});const d=await r.json();showResult(d);}catch(e){showResult({ok:false,message:'Falha de conexão com o servidor.'});}}
async function startCamera(){if(active)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();active=true;note.style.display='none';if('BarcodeDetector'in window){detector=new BarcodeDetector({formats:['qr_code']});scanLoop();}else{loadHtml5Fallback();}}catch(e){showResult({ok:false,message:'Não foi possível abrir a câmera. Em produção use HTTPS e permita o acesso.'});}}
async function scanLoop(){if(!active||!detector)return;try{const codes=await detector.detect(video);if(codes&&codes[0]&&codes[0].rawValue)await sendCode(codes[0].rawValue);}catch(e){}requestAnimationFrame(scanLoop);}
async function stopCamera(){active=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}video.srcObject=null;note.style.display='block';if(h5){try{await h5.stop()}catch(e){}try{await h5.clear()}catch(e){}h5=null;}document.getElementById('html5-reader').style.display='none';document.getElementById('native-reader').style.display='grid';}
function loadHtml5Fallback(){if(window.Html5Qrcode){startHtml5();return;}const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/html5-qrcode/2.3.8/html5-qrcode.min.js';s.integrity='sha512-r6rDA7W6ZeQhvl8S7yRVQUKVHdexq+GAlNkNNqVC7YyIV+NwqCTJe2hDWCiffTyRNOeGEzRRJ9ifvRm/HCzGYg==';s.crossOrigin='anonymous';s.onload=startHtml5;s.onerror=()=>showResult({ok:false,message:'Leitor alternativo indisponível. Use a leitura manual.'});document.head.appendChild(s);}
async function startHtml5(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}video.srcObject=null;document.getElementById('native-reader').style.display='none';const box=document.getElementById('html5-reader');box.style.display='block';try{h5=new Html5Qrcode('html5-reader');active=true;await h5.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},decoded=>sendCode(decoded),()=>{});}catch(e){showResult({ok:false,message:'Não foi possível iniciar o leitor alternativo. Verifique HTTPS e permissão da câmera.'});}}
document.getElementById('start-camera').onclick=startCamera;document.getElementById('stop-camera').onclick=stopCamera;
document.getElementById('manual-form').onsubmit=e=>{e.preventDefault();sendCode(document.getElementById('manual-code').value);};
document.getElementById('qr-photo').onchange=async e=>{const f=e.target.files&&e.target.files[0];if(!f)return;if('BarcodeDetector'in window){try{const bmp=await createImageBitmap(f);const d=new BarcodeDetector({formats:['qr_code']});const codes=await d.detect(bmp);if(codes[0])sendCode(codes[0].rawValue);else showResult({ok:false,message:'Nenhum QR Code encontrado na foto.'});}catch(err){showResult({ok:false,message:'Não foi possível ler a foto.'});}}else if(window.Html5Qrcode){try{const q=new Html5Qrcode('camera-note');const value=await q.scanFile(f,true);sendCode(value);await q.clear();}catch(err){showResult({ok:false,message:'Nenhum QR Code encontrado na foto.'});}}else{showResult({ok:false,message:'Este navegador não oferece leitura de QR por foto. Digite o código manualmente.'});}};
window.addEventListener('beforeunload',stopCamera);
</script>
<?php require '_footer.php';?>
