<?php require __DIR__.'/../lib/bootstrap.php';require_admin();$pageTitle='Dashboard';release_expired_orders();
$metrics=[
'events'=>(int)db()->query("SELECT COUNT(*) FROM events WHERE status='published' AND datetime(event_date)>=datetime('now','-1 day')")->fetchColumn(),
'vip'=>(int)db()->query("SELECT COALESCE(SUM(1+companions),0) FROM vip_entries WHERE status='active'")->fetchColumn(),
'orders'=>(int)db()->query("SELECT COUNT(*) FROM orders WHERE status='pending'")->fetchColumn(),
'revenue'=>(float)db()->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE status='paid'")->fetchColumn(),
'tickets'=>(int)db()->query("SELECT COUNT(*) FROM tickets WHERE status IN ('valid','used')")->fetchColumn(),
'review'=>(int)db()->query("SELECT COUNT(*) FROM orders WHERE status='review' OR requires_review=1")->fetchColumn(),
'email_pending'=>(int)db()->query("SELECT COUNT(*) FROM email_queue WHERE status IN ('pending','failed')")->fetchColumn(),
];
$next=db()->query("SELECT e.*, (SELECT COALESCE(SUM(1+companions),0) FROM vip_entries v WHERE v.event_id=e.id AND v.status!='removed') vip_count, (SELECT COUNT(*) FROM orders o WHERE o.event_id=e.id AND o.status='paid') paid_orders, (SELECT COALESCE(SUM(o.total),0) FROM orders o WHERE o.event_id=e.id AND o.status='paid') revenue FROM events e ORDER BY datetime(e.event_date) DESC LIMIT 8")->fetchAll();
$paymentReady=payment_mode()==='mercadopago' && mp_access_token()!=='' && mp_webhook_secret()!=='' && str_starts_with(payment_base_url(),'https://');require '_header.php';?>
<div class="metric-grid"><div class="metric"><span>Próximos eventos</span><strong><?=$metrics['events']?></strong></div><div class="metric"><span>Pessoas VIP ativas</span><strong><?=$metrics['vip']?></strong></div><div class="metric"><span>Pedidos pendentes</span><strong><?=$metrics['orders']?></strong></div><div class="metric"><span>Em revisão</span><strong><?=$metrics['review']?></strong></div><div class="metric"><span>Receita confirmada</span><strong><?=money($metrics['revenue'])?></strong></div></div>
<div class="admin-card"><div class="card-head"><div><h2>Status operacional</h2><p>Backend, pagamentos e banco local.</p></div><div><a class="btn btn-small btn-secondary" href="backup.php">Backup do banco</a> <a class="btn btn-small btn-secondary" href="../diagnostico.php" target="_blank">Diagnóstico</a></div></div><div class="order-info-grid"><div><small>Modo de pagamento</small><b><?=e(payment_mode()==='mercadopago'?'Mercado Pago':'Manual / caixa')?></b></div><div><small>Venda online</small><b><?=payment_mode()==='mercadopago'?($paymentReady?'✓ configurada':'⚠ falta configurar'):'— modo manual'?></b></div><div><small>Ingressos emitidos</small><b><?=$metrics['tickets']?></b></div><div><small>Banco</small><b>SQLite / WAL</b></div><div><small>E-mail</small><b><?=email_transport_configured()?'✓ '.e(email_transport()):'⚠ pendente'?></b></div><div><small>Fila de e-mail</small><b><?=$metrics['email_pending']?> pendente(s)</b></div></div><?php if(payment_mode()==='mercadopago'&&!$paymentReady):?><div class="alert error">Mercado Pago selecionado, mas faltam Access Token, Webhook Secret e/ou URL pública HTTPS. <a href="settings.php">Configurar agora.</a></div><?php endif;?></div>
<div class="admin-card"><div class="card-head"><h2>Eventos recentes</h2><a class="btn btn-small btn-primary" href="event-form.php">+ Criar evento</a></div><div class="table-wrap"><table><thead><tr><th>Evento</th><th>Data</th><th>Status</th><th>VIP</th><th>Pedidos pagos</th><th>Receita</th><th></th></tr></thead><tbody><?php foreach($next as $ev):?><tr><td><b><?=e($ev['title'])?></b></td><td><?=e(dt_br($ev['event_date']))?></td><td><span class="pill"><?=e(status_label($ev['status']))?></span></td><td><?=intval($ev['vip_count'])?></td><td><?=intval($ev['paid_orders'])?></td><td><?=money((float)$ev['revenue'])?></td><td><a href="event-form.php?id=<?=intval($ev['id'])?>">Editar</a></td></tr><?php endforeach;?></tbody></table></div></div><?php require '_footer.php';?>
