<?php
require __DIR__.'/../lib/bootstrap.php';require_admin();$pageTitle='Produção';
$items=production_checklist();$ready=true;foreach($items as $i)if(!$i[1])$ready=false;
$cronUrl=base_url('cron.php?token='.urlencode(cron_token()));
$webhookUrl=base_url('webhook.php');
require '_header.php';?>
<div class="admin-card"><div class="card-head"><div><h2><?=$ready?'Base técnica pronta':'Checklist antes de publicar'?></h2><p>Itens automáticos que o sistema consegue verificar neste ambiente.</p></div><span class="pill <?=$ready?'paid':'pending'?>"><?=$ready?'PRONTO':'PENDENTE'?></span></div><div class="table-wrap"><table><thead><tr><th>Item</th><th>Status</th><th>Detalhe</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?=e($i[0])?></td><td><b><?=$i[1]?'✓ OK':'✕ PENDENTE'?></b></td><td><?=e((string)$i[2])?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="admin-card"><h2>URLs operacionais</h2><div class="form-grid one"><label>Webhook Mercado Pago<input readonly value="<?=e($webhookUrl)?>" onclick="this.select()"></label><label>Cron secreto (agendar a cada 5 minutos)<input readonly value="<?=e($cronUrl)?>" onclick="this.select()"></label></div><p class="muted">Não publique a URL do cron. Ela contém um token secreto para manutenção automática.</p></div>
<div class="admin-card"><h2>Homologação HostGator</h2><ol class="production-list"><li>No cPanel, usar PHP 8.2 ou 8.3 (recomendado: 8.3).</li><li>Enviar o conteúdo desta pasta diretamente para <code>public_html</code>.</li><li>Confirmar que <code>storage</code> e <code>assets/uploads</code> estão graváveis.</li><li>Apontar o domínio e aguardar a emissão do SSL gratuito; depois habilitar o redirecionamento HTTPS no .htaccess.</li><li>Criar um e-mail no domínio do cliente, por exemplo <code>ingressos@seudominio.com.br</code>, e testar o envio. SMTP recomendado: porta 465/SSL.</li><li>Ative Mercado Pago somente com Access Token e Webhook Secret reais e cadastre a URL de webhook acima.</li><li>No cPanel &gt; Cron Jobs, executar <code>cron.php</code> a cada 5 minutos via PHP CLI.</li><li>Criar um evento de teste com estoque pequeno e fazer uma compra de baixo valor.</li><li>Confirmar e-mail, QR Code, check-in duplicado e reembolso.</li><li>Gerar e guardar um backup antes da abertura oficial das vendas.</li></ol></div>
<div class="admin-card"><h2>Documentos públicos</h2><p><a class="text-link" target="_blank" href="../privacidade.php">Política de Privacidade ↗</a> &nbsp; <a class="text-link" target="_blank" href="../termos.php">Termos de Uso e Compra ↗</a> &nbsp; <a class="text-link" target="_blank" href="../cancelamento.php">Cancelamentos e Reembolsos ↗</a></p></div>
<?php require '_footer.php';?>
