<?php
require __DIR__.'/../lib/bootstrap.php';require_admin();$pageTitle='Personalização e Configurações';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $textKeys=['site_name','site_tagline','site_city_state','site_since','site_description','hero_kicker','hero_title','hero_highlight','hero_text','about_kicker','about_title','about_highlight','about_text','inside_kicker','inside_title','inside_highlight','inside_text','gallery_title','gallery_highlight','gallery_text','location_title','location_highlight','programming_text','address','maps_url','instagram_url','contact_phone','contact_instagram','support_email','privacy_email','legal_name','legal_document','legal_address','smtp_host','smtp_port','smtp_encryption','smtp_username','smtp_from_email','smtp_from_name','smtp_reply_to','terms_version','privacy_version','cancellation_version'];
        foreach($textKeys as $key)set_app_setting($key,trim((string)($_POST[$key]??'')),in_array($key,['smtp_username'],true));
        set_app_setting('contact_whatsapp',normalize_phone($_POST['contact_whatsapp']??''));
        foreach(['brand_primary'=>'#d6a35a','brand_primary_2'=>'#efc67d','brand_rust'=>'#9a4f2e','brand_night'=>'#100908'] as $key=>$fallback)set_app_setting($key,sanitize_hex_color((string)($_POST[$key]??''),$fallback));

        $imageKeys=['brand_logo'=>'logo','hero_image'=>'hero','about_image'=>'about','interior_image'=>'interior','gallery_image_1'=>'gallery-1','gallery_image_2'=>'gallery-2','location_image'=>'location'];
        foreach($imageKeys as $key=>$prefix){
            if(isset($_POST['reset_'.$key])){ $old=app_setting($key,''); delete_uploaded_asset_if_owned($old); set_app_setting($key,match($key){'brand_logo'=>'assets/media/placeholder-logo.svg','hero_image'=>'assets/media/placeholder-hero.svg','about_image'=>'assets/media/placeholder-about.svg','interior_image'=>'assets/media/placeholder-interior.svg','gallery_image_1'=>'assets/media/placeholder-gallery-1.svg','gallery_image_2'=>'assets/media/placeholder-gallery-2.svg','location_image'=>'assets/media/placeholder-location.svg'}); }
            if(!empty($_FILES[$key]['tmp_name'])){ $new=save_uploaded_brand_image($_FILES[$key],$prefix); $old=app_setting($key,''); set_app_setting($key,$new); if($old!==$new)delete_uploaded_asset_if_owned($old); }
        }

        $mode=$_POST['payment_mode']??'manual';if(!in_array($mode,['manual','mercadopago'],true))$mode='manual';set_app_setting('payment_mode',$mode);set_app_setting('app_base_url',rtrim(trim($_POST['app_base_url']??''),'/'));
        $mailTransport=strtolower(trim($_POST['mail_transport']??'phpmail'));if(!in_array($mailTransport,['phpmail','smtp','spool'],true))$mailTransport='phpmail';set_app_setting('mail_transport',$mailTransport);
        if(trim($_POST['mp_access_token']??'')!=='')set_app_setting('mp_access_token',trim($_POST['mp_access_token']),true);if(isset($_POST['clear_mp_access_token']))set_app_setting('mp_access_token','',true);
        if(trim($_POST['mp_webhook_secret']??'')!=='')set_app_setting('mp_webhook_secret',trim($_POST['mp_webhook_secret']),true);if(isset($_POST['clear_mp_webhook_secret']))set_app_setting('mp_webhook_secret','',true);
        if(trim($_POST['smtp_password']??'')!=='')set_app_setting('smtp_password',trim($_POST['smtp_password']),true);if(isset($_POST['clear_smtp_password']))set_app_setting('smtp_password','',true);
        audit_log('settings.updated');flash('success','Personalização e configurações salvas.');redirect('settings.php');
    }catch(Throwable $e){$error=$e->getMessage();}
}
$mode=payment_mode();$hasToken=mp_access_token()!=='';$hasSecret=mp_webhook_secret()!=='';$hasSmtpPass=smtp_setting('password')!=='';
$images=['brand_logo'=>'Logo','hero_image'=>'Foto principal / Hero','about_image'=>'Foto institucional','interior_image'=>'Foto de destaque','gallery_image_1'=>'Galeria 01','gallery_image_2'=>'Galeria 02','location_image'=>'Foto da localização'];
require '_header.php';?>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="admin-form"><?=csrf_field()?>
<div class="admin-card"><div class="card-head"><div><h2>Identidade da marca</h2><p>Troque nome, logo, textos e cores. O site público é atualizado automaticamente.</p></div><button class="btn btn-primary btn-small">Salvar</button></div><div class="form-grid two">
<label>Nome da marca / casa<input name="site_name" value="<?=e(site_name())?>" placeholder="Ex.: Minha Casa de Shows"></label><label>Slogan<input name="site_tagline" value="<?=e(site_tagline())?>" placeholder="Ex.: A noite acontece aqui"></label><label>Cidade / UF<input name="site_city_state" value="<?=e(app_setting('site_city_state','SUA CIDADE / UF'))?>"></label><label>Ano / assinatura<input name="site_since" value="<?=e(app_setting('site_since','DESDE 20XX'))?>"></label><label class="span-2">Descrição do site<input name="site_description" value="<?=e(app_setting('site_description',''))?>"></label>
<label>Cor principal<input type="color" name="brand_primary" value="<?=e(sanitize_hex_color(app_setting('brand_primary','#d6a35a'),'#d6a35a'))?>"></label><label>Cor clara / destaque<input type="color" name="brand_primary_2" value="<?=e(sanitize_hex_color(app_setting('brand_primary_2','#efc67d'),'#efc67d'))?>"></label><label>Cor secundária<input type="color" name="brand_rust" value="<?=e(sanitize_hex_color(app_setting('brand_rust','#9a4f2e'),'#9a4f2e'))?>"></label><label>Cor escura<input type="color" name="brand_night" value="<?=e(sanitize_hex_color(app_setting('brand_night','#100908'),'#100908'))?>"></label>
</div></div>

<div class="admin-card"><div class="card-head"><div><h2>Logo e fotos do site</h2><p>Envie JPG, PNG ou WEBP. Para a logo, prefira PNG com fundo transparente.</p></div></div><div class="brand-media-grid">
<?php foreach($images as $key=>$label):$current=app_setting($key,'');?><label class="brand-upload-card"><strong><?=e($label)?></strong><span class="brand-preview"><img src="../<?=e($current)?>" alt="<?=e($label)?>"></span><input type="file" name="<?=e($key)?>" accept="image/jpeg,image/png,image/webp"><span class="field-hint"><?=e($current)?></span><span class="check-line"><input type="checkbox" name="reset_<?=e($key)?>"> Voltar para placeholder</span></label><?php endforeach;?>
</div></div>

<div class="admin-card"><div class="card-head"><div><h2>Textos da página inicial</h2><p>Você pode transformar o mesmo sistema em bar, balada, casa de shows, festival, arena ou produtor de eventos.</p></div></div><div class="form-grid two">
<label>Kicker da abertura<input name="hero_kicker" value="<?=e(app_setting('hero_kicker',''))?>"></label><label>Título principal<input name="hero_title" value="<?=e(app_setting('hero_title',''))?>"></label><label>Destaque do título<input name="hero_highlight" value="<?=e(app_setting('hero_highlight',''))?>"></label><label class="span-2">Texto principal<textarea name="hero_text" rows="3"><?=e(app_setting('hero_text',''))?></textarea></label>
<label>Kicker “Sobre”<input name="about_kicker" value="<?=e(app_setting('about_kicker',''))?>"></label><label>Título “Sobre”<input name="about_title" value="<?=e(app_setting('about_title',''))?>"></label><label>Destaque “Sobre”<input name="about_highlight" value="<?=e(app_setting('about_highlight',''))?>"></label><label class="span-2">Texto “Sobre”<textarea name="about_text" rows="4"><?=e(app_setting('about_text',''))?></textarea></label>
<label>Kicker destaque<input name="inside_kicker" value="<?=e(app_setting('inside_kicker',''))?>"></label><label>Título destaque<input name="inside_title" value="<?=e(app_setting('inside_title',''))?>"></label><label>Destaque do título<input name="inside_highlight" value="<?=e(app_setting('inside_highlight',''))?>"></label><label class="span-2">Texto destaque<textarea name="inside_text" rows="3"><?=e(app_setting('inside_text',''))?></textarea></label>
<label>Título galeria<input name="gallery_title" value="<?=e(app_setting('gallery_title',''))?>"></label><label>Destaque galeria<input name="gallery_highlight" value="<?=e(app_setting('gallery_highlight',''))?>"></label><label class="span-2">Texto galeria<textarea name="gallery_text" rows="3"><?=e(app_setting('gallery_text',''))?></textarea></label>
<label>Título localização<input name="location_title" value="<?=e(app_setting('location_title',''))?>"></label><label>Destaque localização<input name="location_highlight" value="<?=e(app_setting('location_highlight',''))?>"></label><label class="span-2">Texto de programação<input name="programming_text" value="<?=e(app_setting('programming_text',''))?>"></label>
</div></div>

<div class="admin-card"><div class="card-head"><div><h2>Local e contato</h2><p>Informações exibidas no site e nas comunicações.</p></div></div><div class="form-grid two"><label>Endereço<input name="address" value="<?=e(app_setting('address',$config['address']??''))?>"></label><label>Link do Google Maps<input name="maps_url" value="<?=e(app_setting('maps_url',''))?>" placeholder="https://maps.google.com/..."></label><label>Telefone<input name="contact_phone" value="<?=e(app_setting('contact_phone',''))?>"></label><label>WhatsApp<input name="contact_whatsapp" value="<?=e(app_setting('contact_whatsapp',''))?>"></label><label>Instagram / @<input name="contact_instagram" value="<?=e(app_setting('contact_instagram',''))?>"></label><label>Link do Instagram<input name="instagram_url" value="<?=e(app_setting('instagram_url',''))?>"></label><label>E-mail de suporte<input type="email" name="support_email" value="<?=e(app_setting('support_email',''))?>"></label><label>E-mail de privacidade/LGPD<input type="email" name="privacy_email" value="<?=e(app_setting('privacy_email',''))?>"></label></div></div>

<div class="admin-card"><div class="card-head"><div><h2>Venda online</h2><p>Mercado Pago é opcional. O modo manual permite homologar o sistema antes de conectar uma conta real.</p></div></div><div class="form-grid two"><label>Modo de pagamento<select name="payment_mode"><option value="manual" <?=$mode==='manual'?'selected':''?>>Manual / caixa</option><option value="mercadopago" <?=$mode==='mercadopago'?'selected':''?>>Mercado Pago Checkout Pro</option></select></label><label>URL pública da aplicação<input name="app_base_url" value="<?=e(app_setting('app_base_url',''))?>" placeholder="https://eventos.seudominio.com.br"></label><label>Access Token Mercado Pago<input type="password" name="mp_access_token" placeholder="<?=$hasToken?'Token já salvo — deixe em branco para manter':'APP_USR-...'?>" autocomplete="off"><span class="field-hint"><?=$hasToken?'✓ credencial cadastrada':'não configurado'?></span></label><label>Webhook Secret<input type="password" name="mp_webhook_secret" placeholder="<?=$hasSecret?'Secret já salvo — deixe em branco para manter':'secret do webhook'?>" autocomplete="off"><span class="field-hint"><?=$hasSecret?'✓ secret cadastrado':'não configurado'?></span></label><label class="check-line"><input type="checkbox" name="clear_mp_access_token"> Remover Access Token</label><label class="check-line"><input type="checkbox" name="clear_mp_webhook_secret"> Remover Webhook Secret</label></div></div>

<div class="admin-card"><div class="card-head"><div><h2>E-mail transacional</h2><p>Use PHP mail() da hospedagem ou SMTP autenticado.</p></div><a class="btn btn-secondary btn-small" href="email.php">Fila e teste</a></div><div class="form-grid two"><label>Método<select name="mail_transport"><option value="phpmail" <?=email_transport()==='phpmail'?'selected':''?>>PHP mail() / hospedagem</option><option value="smtp" <?=email_transport()==='smtp'?'selected':''?>>SMTP autenticado</option><option value="spool" <?=email_transport()==='spool'?'selected':''?>>Spool local / homologação</option></select></label><label>Servidor SMTP<input name="smtp_host" value="<?=e(smtp_setting('host'))?>"></label><label>Porta<input type="number" name="smtp_port" value="<?=e(smtp_setting('port','465'))?>"></label><label>Criptografia<select name="smtp_encryption"><option value="tls" <?=smtp_setting('encryption','tls')==='tls'?'selected':''?>>STARTTLS (587)</option><option value="ssl" <?=smtp_setting('encryption')==='ssl'?'selected':''?>>SSL/TLS direto (465)</option><option value="none" <?=smtp_setting('encryption')==='none'?'selected':''?>>Sem criptografia</option></select></label><label>Usuário SMTP<input name="smtp_username" value="<?=e(smtp_setting('username'))?>"></label><label>Senha SMTP<input type="password" name="smtp_password" placeholder="<?=$hasSmtpPass?'Senha salva — deixe em branco para manter':'senha do e-mail'?>"></label><label class="check-line"><input type="checkbox" name="clear_smtp_password"> Remover senha SMTP</label><label>E-mail remetente<input type="email" name="smtp_from_email" value="<?=e(smtp_setting('from_email'))?>"></label><label>Nome remetente<input name="smtp_from_name" value="<?=e(smtp_setting('from_name',site_name()))?>"></label><label>Reply-To<input type="email" name="smtp_reply_to" value="<?=e(smtp_setting('reply_to'))?>"></label></div></div>

<div class="admin-card"><div class="card-head"><div><h2>Dados legais</h2><p>Preencha com os dados reais do cliente antes de publicar.</p></div></div><div class="form-grid two"><label>Razão social / nome empresarial<input name="legal_name" value="<?=e(app_setting('legal_name',''))?>"></label><label>CNPJ/CPF da operação<input name="legal_document" value="<?=e(app_setting('legal_document',''))?>"></label><label class="span-2">Endereço legal<input name="legal_address" value="<?=e(app_setting('legal_address',''))?>"></label><label>Versão dos Termos<input name="terms_version" value="<?=e(legal_version('terms'))?>"></label><label>Versão da Privacidade<input name="privacy_version" value="<?=e(legal_version('privacy'))?>"></label><label>Versão de Cancelamento<input name="cancellation_version" value="<?=e(legal_version('cancellation'))?>"></label></div></div>
<div class="sticky-save"><button class="btn btn-primary">Salvar tudo</button><a class="btn btn-secondary" href="../index.php" target="_blank">Visualizar site ↗</a><a class="btn btn-secondary" href="production.php">Checklist de produção</a></div></form><?php require '_footer.php';?>
