<?php require __DIR__.'/../lib/bootstrap.php';require_admin();$pageTitle='Importar Lista VIP';$eventId=(int)($_GET['event']??$_POST['event_id']??0);$error='';$result=null;$events=db()->query("SELECT id,title,event_date FROM events WHERE vip_enabled=1 ORDER BY datetime(event_date) DESC")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$event=event_by_id($eventId);if(!$event||!(int)$event['vip_enabled'])$error='Selecione um evento com Lista VIP habilitada.';elseif(empty($_FILES['csv']['tmp_name'])||!is_uploaded_file($_FILES['csv']['tmp_name']))$error='Selecione um arquivo CSV.';else{try{
  $fh=fopen($_FILES['csv']['tmp_name'],'r');if(!$fh)throw new RuntimeException('Não foi possível ler o CSV.');$first=fgets($fh);rewind($fh);$delimiter=substr_count((string)$first,';')>=substr_count((string)$first,',')?';':',';$rows=[];$header=fgetcsv($fh,0,$delimiter,'"','');if(!$header)throw new RuntimeException('CSV vazio.');$header=array_map(fn($v)=>strtolower(trim((string)$v)), $header);$map=[];foreach($header as $i=>$h){$h=str_replace(['á','ã','â','é','ê','í','ó','ô','õ','ú','ç'],['a','a','a','e','e','i','o','o','o','u','c'],$h);$map[$h]=$i;}
  $nameIdx=$map['nome']??$map['name']??null;if($nameIdx===null)throw new RuntimeException('O CSV precisa ter uma coluna "Nome". Colunas opcionais: Documento, Email, Telefone, Acompanhantes, Observacoes.');$inserted=0;$skipped=0;$people=vip_people_count($eventId);$cap=(int)$event['vip_capacity'];
  while(($r=fgetcsv($fh,0,$delimiter,'"',''))!==false){$name=trim((string)($r[$nameIdx]??''));if($name==='')continue;$doc=trim((string)($r[$map['documento']??-1]??''));$email=trim((string)($r[$map['email']??-1]??''));$phone=trim((string)($r[$map['telefone']??-1]??''));$comp=max(0,min(20,(int)($r[$map['acompanhantes']??-1]??0)));$notes=trim((string)($r[$map['observacoes']??-1]??''));if($cap>0&&$people+1+$comp>$cap){$skipped++;continue;}$dup=false;if($email!==''||normalize_document($doc)!==''){$st=db()->prepare("SELECT 1 FROM vip_entries WHERE event_id=? AND status!='removed' AND ((?<>'' AND lower(email)=lower(?)) OR (?<>'' AND replace(replace(replace(document,'.',''),'-',''),'/','')=?)) LIMIT 1");$dn=normalize_document($doc);$st->execute([$eventId,$email,$email,$dn,$dn]);$dup=(bool)$st->fetchColumn();}if($dup){$skipped++;continue;}db()->prepare('INSERT INTO vip_entries(event_id,name,document,email,phone,companions,notes,status) VALUES(?,?,?,?,?,?,?,"active")')->execute([$eventId,$name,$doc,$email,$phone,$comp,$notes]);$inserted++;$people+=1+$comp;}
  fclose($fh);audit_log('vip.import','event',$eventId,['inserted'=>$inserted,'skipped'=>$skipped]);$result=['inserted'=>$inserted,'skipped'=>$skipped];
 }catch(Throwable $e){$error=$e->getMessage();}}
}
require '_header.php';?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><?php if($result):?><div class="alert success"><?=intval($result['inserted'])?> cadastro(s) importado(s); <?=intval($result['skipped'])?> ignorado(s) por duplicidade/capacidade.</div><?php endif;?><div class="admin-card narrow-card"><div class="card-head"><div><h2>Importar CSV</h2><p>Use cabeçalho: Nome; Documento; Email; Telefone; Acompanhantes; Observacoes.</p></div></div><form method="post" enctype="multipart/form-data" class="form-grid one"><?=csrf_field()?><label>Evento<select name="event_id" required><option value="">Selecione</option><?php foreach($events as $ev):?><option value="<?=intval($ev['id'])?>" <?=$eventId===(int)$ev['id']?'selected':''?>><?=e($ev['title'])?> — <?=date_br($ev['event_date'])?></option><?php endforeach;?></select></label><label>Arquivo CSV<input type="file" name="csv" accept=".csv,text/csv" required></label><button class="btn btn-primary">Importar lista</button></form></div><?php require '_footer.php';?>
