name: Deploy to Netlify

on:
  push:
    branches:
      - main # Se a sua branch principal se chamar master, troque aqui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # IMPORTANTE: Se o seu projeto precisa de npm install e npm run build (ex: Next.js, Vite),
      # remova o '#' das 8 linhas abaixo para ativá-las:
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Instalar e Buildar
      #   run: |
      #     npm install
      #     npm run build

      - name: Deploy para o Netlify
        run: npx netlify-cli deploy --prod --dir=. --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --message "Deploy via GH Actions"
